{
    'name': 'DMS 銷售管理',
    'version': '16.0.2.0.0',
    'summary': '銷售訂單、精品明細、產品管理、價目管理',
    'author': 'DMIS',
    'license': 'LGPL-3',
    'category': 'Custom',
    'depends': ['dms_core', 'dms_customer'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/system_parameters.xml',
        'data/scheduled_action.xml',
        'views/product_views.xml',
        'views/product_kanban_config_views.xml',
        'views/accessory_views.xml',
        'views/vehicle_price_views.xml',
        'views/fee_schedule_views.xml',
        'views/commission_rule_views.xml',
        'views/sale_order_views.xml',
        'views/ev_password_wizard_views.xml',
        'views/vehicle_color_views.xml',
        'views/product_pricelist_menu.xml',
        'views/order_sync_log_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dms_sale/static/src/css/product_kanban.css',
            'dms_sale/static/src/js/dms_product_column_limit.js',
            'dms_sale/static/src/js/product_image_lightbox.js',
        ],
    },
    'installable': True,
    'application': True,
}
