from django.urls import reverse

from .app_version import get_app_version


HELP_TOPIC_BY_ROUTE = {
    "dashboard": "dashboard",
    "order_list": "search-orders",
    "order_create": "create-order",
    "order_edit": "create-order",
    "order_detail": "order-work",
    "allocate_vehicle": "allocation",
    "reallocate_vehicle": "allocation",
    "order_operations": "operations",
    "operations_report": "operations",
    "reconciliation_list": "reconciliation",
    "inventory_list": "inventory",
    "inventory_create": "inventory",
    "inventory_quick_create": "inventory",
    "inventory_edit": "inventory",
    "customer_list": "master-data",
    "customer_detail": "master-data",
    "vehicle_model_list": "master-data",
    "vehicle_model_create": "master-data",
    "vehicle_model_edit": "master-data",
    "dealer_price_list_list": "master-data",
    "dealer_price_list_workspace": "master-data",
    "dealer_price_list_print": "master-data",
    "accessory_product_list": "master-data",
    "accessory_product_create": "master-data",
    "accessory_product_edit": "master-data",
    "data_maintenance": "master-data",
    "legacy_import_list": "import-data",
    "legacy_import_detail": "import-data",
    "positioned_template_list": "print-templates",
    "positioned_template_create": "print-templates",
    "positioned_template_edit": "print-templates",
    "sales_source_list": "master-data",
    "sales_source_category_list": "master-data",
    "sales_source_create": "master-data",
    "sales_source_edit": "master-data",
    "installment_company_list": "master-data",
    "vehicle_installment_plan_list": "master-data",
    "dealer_volume_bonus_list": "master-data",
    "dealer_volume_bonus_create": "master-data",
    "dealer_volume_bonus_edit": "master-data",
    "dealer_volume_bonus_settle": "master-data",
    "dealer_volume_bonus_revise": "master-data",
    "business_holiday_list": "master-data",
    "brand_registration_fee_rule_list": "master-data",
    "settlement_cost_rule_list": "master-data",
    "settlement_cost_rule_create": "master-data",
    "settlement_cost_rule_edit": "master-data",
    "incentive_rule_list": "master-data",
    "incentive_rule_create": "master-data",
    "incentive_rule_edit": "master-data",
}


DATA_MAINTENANCE_ROUTES = {
    "data_maintenance",
    "customer_list",
    "customer_detail",
    "inventory_list",
    "inventory_create",
    "inventory_quick_create",
    "inventory_edit",
    "vehicle_model_list",
    "vehicle_model_create",
    "vehicle_model_edit",
    "dealer_price_list_list",
    "dealer_price_list_workspace",
    "dealer_price_list_print",
    "accessory_product_list",
    "accessory_product_create",
    "accessory_product_edit",
    "settlement_cost_rule_list",
    "settlement_cost_rule_create",
    "settlement_cost_rule_edit",
    "incentive_rule_list",
    "incentive_rule_create",
    "incentive_rule_edit",
    "sales_source_list",
    "sales_source_category_list",
    "sales_source_create",
    "sales_source_edit",
    "installment_company_list",
    "vehicle_installment_plan_list",
    "dealer_volume_bonus_list",
    "dealer_volume_bonus_create",
    "dealer_volume_bonus_edit",
    "dealer_volume_bonus_settle",
    "dealer_volume_bonus_revise",
    "business_holiday_list",
    "brand_registration_fee_rule_list",
    "legacy_import_list",
    "legacy_import_detail",
    "positioned_template_list",
    "positioned_template_create",
    "positioned_template_edit",
    "positioned_template_preview",
    "positioned_template_order_print",
}


def app_version(request):
    route_name = getattr(getattr(request, "resolver_match", None), "url_name", None)
    topic = HELP_TOPIC_BY_ROUTE.get(route_name, "quick-start")
    return {
        "app_version": get_app_version(),
        "context_help_url": f"{reverse('user_guide')}#{topic}",
        "is_data_maintenance_section": route_name in DATA_MAINTENANCE_ROUTES,
        "request_id": getattr(request, "request_id", ""),
    }
