from . import product_template
from . import price_version
from . import price_line
from . import installment_rule
from . import installment_rule_line
from . import fee_type
from . import installment_rule_fee
from . import installment_rule_binding
from . import product_compat
