# Generated by Django 5.1.15 on 2026-07-28 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=24,
                        unique=True,
                        verbose_name="訂單編號",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="訂單日期"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("store", "本店"),
                            ("dealer", "合作車行"),
                            ("platform", "網路平台"),
                        ],
                        default="store",
                        max_length=20,
                        verbose_name="訂單來源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("contract_pending", "待簽署合約"),
                            ("allocation_pending", "待配車"),
                            ("allocated", "已配車"),
                            ("transfer_pending", "待調車"),
                            ("in_transfer", "調車中"),
                            ("delivery_pending", "待交車"),
                            ("delivered_docs_pending", "已交車／待補文件"),
                            ("completed", "已完成"),
                            ("cancel_refund_pending", "取消待退款"),
                            ("cancelled", "已取消／已退款"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="訂單狀態",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("local", "本國自然人"),
                            ("foreign", "外籍／居留者"),
                            ("company", "法人"),
                        ],
                        default="local",
                        max_length=20,
                        verbose_name="車主類型",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=160, verbose_name="車主姓名／公司名稱"),
                ),
                (
                    "owner_name_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="英文姓名"
                    ),
                ),
                ("owner_phone", models.CharField(max_length=30, verbose_name="電話")),
                (
                    "owner_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "owner_birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "owner_nationality",
                    models.CharField(blank=True, max_length=80, verbose_name="國籍"),
                ),
                ("owner_address", models.TextField(verbose_name="戶籍／公司地址")),
                (
                    "owner_id_number",
                    models.CharField(max_length=40, verbose_name="證件號碼／統一編號"),
                ),
                (
                    "residence_expiry",
                    models.DateField(blank=True, null=True, verbose_name="居留期限"),
                ),
                (
                    "id_front",
                    models.ImageField(
                        blank=True,
                        upload_to="orders/id/%Y/%m/",
                        verbose_name="證件正面",
                    ),
                ),
                (
                    "id_back",
                    models.ImageField(
                        blank=True,
                        upload_to="orders/id/%Y/%m/",
                        verbose_name="證件反面",
                    ),
                ),
                (
                    "id_verified",
                    models.BooleanField(default=False, verbose_name="已人工核對證件"),
                ),
                (
                    "id_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="證件核對時間"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("cash", "全現金"), ("installment", "全分期")],
                        default="cash",
                        max_length=20,
                        verbose_name="主要付款方式",
                    ),
                ),
                (
                    "vehicle_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="車價"
                    ),
                ),
                (
                    "plate_insurance_fee",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="牌險"
                    ),
                ),
                (
                    "installment_opening_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="分期開辦費",
                    ),
                ),
                (
                    "other_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="其他費用",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣／抵扣",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="訂金"
                    ),
                ),
                (
                    "deposit_date",
                    models.DateField(blank=True, null=True, verbose_name="訂金日期"),
                ),
                (
                    "deposit_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "現金"),
                            ("transfer", "匯款"),
                            ("card", "刷卡"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="訂金付款方式",
                    ),
                ),
                (
                    "calculated_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="系統試算尾款",
                    ),
                ),
                (
                    "actual_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="實際尾款",
                    ),
                ),
                (
                    "balance_adjustment_reason",
                    models.TextField(blank=True, verbose_name="尾款調整原因"),
                ),
                (
                    "installment_company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="融資公司"
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="分期申請金額",
                    ),
                ),
                (
                    "installment_periods",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="分期期數"
                    ),
                ),
                (
                    "installment_monthly",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="每期金額",
                    ),
                ),
                (
                    "installment_applied_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="分期申請日期"
                    ),
                ),
                (
                    "installment_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="分期狀態"
                    ),
                ),
                (
                    "installment_decided_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="核准／拒絕日期"
                    ),
                ),
                (
                    "is_trade_in_subsidy",
                    models.BooleanField(
                        default=False, verbose_name="申請汰舊／政府補助"
                    ),
                ),
                (
                    "trade_in_plate",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="舊車車牌"
                    ),
                ),
                (
                    "subsidy_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="補助類型"
                    ),
                ),
                (
                    "old_vehicle_valuation",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="舊車估價",
                    ),
                ),
                (
                    "old_vehicle_tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="舊車未繳稅金",
                    ),
                ),
                (
                    "plate_choice",
                    models.CharField(
                        choices=[
                            ("none", "不選號"),
                            ("watch", "指定號碼監控"),
                            ("preference", "一般領牌偏好"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="選號方式",
                    ),
                ),
                (
                    "watched_numbers",
                    models.TextField(blank=True, verbose_name="指定號碼與志願序"),
                ),
                (
                    "plate_preference_note",
                    models.TextField(blank=True, verbose_name="領牌偏好備註"),
                ),
                (
                    "final_plate_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="最終車牌號碼"
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="交車方式"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                (
                    "signed_contract",
                    models.FileField(
                        blank=True,
                        upload_to="orders/contracts/%Y/%m/",
                        verbose_name="已簽署合約",
                    ),
                ),
                (
                    "signed_contract_uploaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="合約上傳時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "銷售訂單",
                "verbose_name_plural": "銷售訂單",
                "ordering": ["-order_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="門市名稱"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="門市代碼"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
            ],
            options={
                "verbose_name": "門市",
                "verbose_name_plural": "門市",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VehicleColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="車色")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
            ],
            options={
                "verbose_name": "車色",
                "verbose_name_plural": "車色",
                "ordering": ["vehicle_model", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="事件類型"),
                ),
                ("description", models.TextField(verbose_name="內容")),
                (
                    "actor_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="操作人員"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單事件",
                "verbose_name_plural": "訂單事件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccessoryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="配件名稱")),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=1, verbose_name="數量"),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[("purchase", "加購"), ("gift", "贈送")],
                        default="purchase",
                        max_length=20,
                        verbose_name="類型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="金額"
                    ),
                ),
                (
                    "installed_on",
                    models.DateField(blank=True, null=True, verbose_name="安裝日期"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="備註"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessories",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "配件",
                "verbose_name_plural": "配件",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SalesSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="來源名稱")),
                (
                    "source_type",
                    models.CharField(
                        choices=[("dealer", "合作車行"), ("platform", "網路平台")],
                        max_length=20,
                        verbose_name="來源類型",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
            ],
            options={
                "verbose_name": "訂單來源",
                "verbose_name_plural": "訂單來源",
                "ordering": ["source_type", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_type", "name"), name="unique_sales_source_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.salessource",
                verbose_name="來源名稱",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="selling_store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="sales.store",
                verbose_name="銷售門市",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.vehiclecolor",
                verbose_name="車色",
            ),
        ),
        migrations.CreateModel(
            name="VehicleInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "engine_number",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="引擎號碼",
                    ),
                ),
                (
                    "frame_number",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="車身號碼",
                    ),
                ),
                (
                    "received_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="進車日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可銷售"),
                            ("reserved", "已預留"),
                            ("transfer_pending", "待調車"),
                            ("in_transfer", "調車中"),
                            ("delivery_pending", "待交車"),
                            ("delivered", "已交車"),
                            ("condition_issue", "車況異常"),
                            ("sold", "已售出"),
                            ("inactive", "停用"),
                        ],
                        default="available",
                        max_length=30,
                        verbose_name="庫存狀態",
                    ),
                ),
                (
                    "condition_note",
                    models.TextField(blank=True, verbose_name="車況說明"),
                ),
                (
                    "condition_photo",
                    models.ImageField(
                        blank=True,
                        upload_to="inventory/condition/%Y/%m/",
                        verbose_name="車況照片",
                    ),
                ),
                (
                    "condition_resolution",
                    models.TextField(blank=True, verbose_name="處理結果"),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.vehiclecolor",
                        verbose_name="車色",
                    ),
                ),
                (
                    "location_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="located_vehicles",
                        to="sales.store",
                        verbose_name="實際存放門市",
                    ),
                ),
                (
                    "ownership_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_vehicles",
                        to="sales.store",
                        verbose_name="庫存歸屬門市",
                    ),
                ),
            ],
            options={
                "verbose_name": "實體庫存車輛",
                "verbose_name_plural": "實體庫存車輛",
                "ordering": ["-received_on", "-id"],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="allocated_vehicle",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_order",
                to="sales.vehicleinventory",
                verbose_name="已配車輛",
            ),
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="廠牌")),
                ("name", models.CharField(max_length=120, verbose_name="車型")),
                (
                    "energy_type",
                    models.CharField(
                        choices=[("gas", "油車"), ("electric", "電動車")],
                        max_length=20,
                        verbose_name="動力類型",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
            ],
            options={
                "verbose_name": "車型",
                "verbose_name_plural": "車型",
                "ordering": ["brand", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "name"), name="unique_vehicle_model"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="vehicle_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.vehiclemodel",
                verbose_name="車型",
            ),
        ),
        migrations.AddField(
            model_name="vehiclecolor",
            name="vehicle_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colors",
                to="sales.vehiclemodel",
                verbose_name="車型",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="vehicle_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.vehiclemodel",
                verbose_name="車型",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclecolor",
            constraint=models.UniqueConstraint(
                fields=("vehicle_model", "name"), name="unique_model_color"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["number"], name="sales_sales_number_542e21_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["owner_name"], name="sales_sales_owner_n_7e4793_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["owner_phone"], name="sales_sales_owner_p_932bad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["owner_id_number"], name="sales_sales_owner_i_983b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["status"], name="sales_sales_status_480214_idx"),
        ),
    ]
