# Generated by Django 5.1.15 on 2026-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("store_pickup", "客人來店取車"),
                    ("dealer_pickup", "合作車行領車"),
                    ("direct_delivery", "送至指定地點"),
                    ("carrier", "委託託運公司"),
                ],
                max_length=30,
                verbose_name="交車方式",
            ),
        ),
    ]
