# Generated by Django 5.1.15 on 2026-07-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_salesorder_delivery_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesorder",
            name="selling_store",
        ),
    ]
