# Generated by Django 5.1.15 on 2026-07-28 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_remove_salesorder_selling_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDraft",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="草稿內容"),
                ),
                (
                    "id_front",
                    models.ImageField(
                        blank=True,
                        upload_to="drafts/id/%Y/%m/",
                        verbose_name="證件正面",
                    ),
                ),
                (
                    "id_back",
                    models.ImageField(
                        blank=True,
                        upload_to="drafts/id/%Y/%m/",
                        verbose_name="證件反面",
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(default=1, verbose_name="版本"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="建立人員"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="最後編輯人員"
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單草稿",
                "verbose_name_plural": "訂單草稿",
                "ordering": ["-updated_at"],
            },
        ),
    ]
