# Generated by Django 5.1.15 on 2026-07-28 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_orderdraft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesorder",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="salesorder",
            name="other_fee",
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="deposit_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.localdate,
                null=True,
                verbose_name="訂金日期",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "現金"), ("installment", "分期"), ("card", "刷卡")],
                default="cash",
                max_length=20,
                verbose_name="主要付款方式",
            ),
        ),
        migrations.CreateModel(
            name="OtherFeeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="費用項目")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="金額"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_fees",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "其他費用",
                "verbose_name_plural": "其他費用",
                "ordering": ["id"],
            },
        ),
    ]
