# Generated by Django 5.1.15 on 2026-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_remove_salesorder_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="installment_company",
            field=models.CharField(blank=True, max_length=100, verbose_name="分期公司"),
        ),
    ]
