# Generated by Django 5.1.15 on 2026-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_salesorder_installment_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="delivery_destination",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="送達地點／託運目的地"
            ),
        ),
    ]
