# Generated by Django 5.1.15 on 2026-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_salesorder_delivery_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdraft",
            name="editing_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後編輯心跳"
            ),
        ),
        migrations.AddField(
            model_name="orderdraft",
            name="editing_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="目前編輯人員"
            ),
        ),
        migrations.AddField(
            model_name="orderdraft",
            name="editing_session",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="編輯工作階段"
            ),
        ),
    ]
