# Generated by Django 5.1.15 on 2026-07-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_orderdraft_editing_at_orderdraft_editing_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftFieldPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="編輯工作階段"),
                ),
                (
                    "client_id",
                    models.CharField(max_length=64, verbose_name="瀏覽器連線"),
                ),
                (
                    "field_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="目前欄位"
                    ),
                ),
                (
                    "editing_by",
                    models.CharField(max_length=150, verbose_name="編輯人員"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="識別顏色"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最後活動時間"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_presences",
                        to="sales.orderdraft",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "session_key", "client_id"),
                        name="unique_draft_editor_client",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DraftFieldState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_key",
                    models.CharField(max_length=200, verbose_name="欄位識別碼"),
                ),
                ("value", models.JSONField(default=str, verbose_name="欄位值")),
                (
                    "version",
                    models.PositiveIntegerField(default=0, verbose_name="欄位版本"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="最後編輯人員"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_states",
                        to="sales.orderdraft",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("draft", "field_key"), name="unique_draft_field_state"
                    )
                ],
            },
        ),
    ]
