# Generated by Django 5.1.15 on 2026-07-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_salesorder_privacy_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="compulsory_insurance_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="強制險"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="compulsory_insurance_period",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "一年"), (2, "兩年")], default=1, verbose_name="強制險期間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="license_tax_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="使用牌照稅"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="lien_registration_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="動保設定費"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="plate_selection_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="選號費"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_calculated_total",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="系統試算牌險合計",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_date",
            field=models.DateField(blank=True, null=True, verbose_name="預計領牌日期"),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_inspection_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="檢驗費"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_license_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="行照費"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_plate_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="號牌費"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_rate_class",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="領牌費率級距"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="road_maintenance_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="公路養管費"
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="displacement_cc",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="油車領牌試算使用；電動車與微型電動二輪車可留空。",
                null=True,
                verbose_name="排氣量（c.c.）",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="plate_insurance_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="實際牌險合計"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="energy_type",
            field=models.CharField(
                choices=[
                    ("gas", "油車"),
                    ("electric", "電動車"),
                    ("micro_electric", "微型電動二輪車"),
                ],
                max_length=20,
                verbose_name="動力類型",
            ),
        ),
    ]
