# Generated by Django 5.1.15 on 2026-07-29 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_clear_non_installment_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="registration_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="領牌完成時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_completed_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="領牌完成人員"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="registration_date",
            field=models.DateField(blank=True, null=True, verbose_name="實際領牌日期"),
        ),
        migrations.CreateModel(
            name="RegistrationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("new_license", "新行照照片"),
                            ("registration_application", "新車領牌登記書"),
                            ("motor_vehicle_receipt", "監理站單據"),
                            ("invoice", "發票"),
                            ("compulsory_insurance", "強制險單"),
                            ("plate_selection", "選號單"),
                            ("other_insurance", "其他保險單"),
                        ],
                        max_length=40,
                        verbose_name="文件類型",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="文件名稱"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="orders/registration/%Y/%m/", verbose_name="檔案"
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="上傳人員"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_documents",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "領牌文件",
                "verbose_name_plural": "領牌文件",
                "ordering": ["document_type", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("document_type", "other_insurance"), _negated=True
                        ),
                        fields=("order", "document_type"),
                        name="unique_fixed_registration_document",
                    )
                ],
            },
        ),
    ]
