# Generated by Django 5.1.15 on 2026-07-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_salesorder_registration_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("old_owner_id_front", "舊車主身分證正面"),
                            ("old_owner_id_back", "舊車主身分證反面"),
                            ("old_vehicle_registration", "舊車行照"),
                            ("scrap_certificate", "報廢證明"),
                            ("recycling_receipt", "回收管制聯"),
                            ("owner_declaration", "新舊車主不同人聲明書"),
                        ],
                        max_length=40,
                        verbose_name="文件類型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="orders/subsidy/%Y/%m/", verbose_name="檔案"
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="上傳人員"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_documents",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "汰舊補助文件",
                "verbose_name_plural": "汰舊補助文件",
                "ordering": ["document_type", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "document_type"),
                        name="unique_subsidy_document",
                    )
                ],
            },
        ),
    ]
