# Generated by Django 5.1.15 on 2026-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_subsidydocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsidydocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("old_owner_id_front", "舊車主身分證正面"),
                    ("old_owner_id_back", "舊車主身分證反面"),
                    ("old_vehicle_registration", "舊車行照"),
                    ("scrap_certificate", "報廢證明"),
                    ("recycling_receipt", "回收管制聯"),
                    ("new_owner_bankbook", "新車主存摺封面"),
                    ("old_owner_bankbook", "舊車主存摺封面"),
                    ("owner_declaration", "新舊車主不同人聲明書"),
                ],
                max_length=40,
                verbose_name="文件類型",
            ),
        ),
    ]
