# Generated by Django 5.1.15 on 2026-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0017_alter_subsidydocument_document_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subsidydocument",
            name="unique_subsidy_document",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="old_owner_id_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="舊車主身分證字號"
            ),
        ),
        migrations.AddField(
            model_name="subsidydocument",
            name="name",
            field=models.CharField(blank=True, max_length=160, verbose_name="文件名稱"),
        ),
        migrations.AddField(
            model_name="subsidydocument",
            name="note",
            field=models.CharField(blank=True, max_length=250, verbose_name="備註"),
        ),
        migrations.AlterField(
            model_name="subsidydocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("old_owner_id_front", "舊車主身分證正面"),
                    ("old_owner_id_back", "舊車主身分證反面"),
                    ("old_vehicle_registration", "舊車行照"),
                    ("scrap_certificate", "報廢證明"),
                    ("recycling_receipt", "回收管制聯"),
                    ("new_owner_bankbook", "新車主存摺封面"),
                    ("old_owner_bankbook", "舊車主存摺封面"),
                    ("owner_declaration", "新舊車主不同人聲明書"),
                    ("other", "其他補助文件"),
                ],
                max_length=40,
                verbose_name="文件類型",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsidydocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document_type", "other"), _negated=True),
                fields=("order", "document_type"),
                name="unique_subsidy_document",
            ),
        ),
    ]
