# Generated by Django 5.1.15 on 2026-07-29 12:20

from django.db import migrations, models


def infer_existing_owner_relationship(apps, schema_editor):
    SalesOrder = apps.get_model("sales", "SalesOrder")
    for order in SalesOrder.objects.exclude(old_owner_name="").iterator():
        same_owner = order.old_owner_name.strip() == order.owner_name.strip()
        if order.old_owner_same_as_owner != same_owner:
            order.old_owner_same_as_owner = same_owner
            order.save(update_fields=["old_owner_same_as_owner"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0018_remove_subsidydocument_unique_subsidy_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="old_owner_ocr_id_number",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="OCR 辨識舊車主身分證字號"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="old_owner_ocr_name",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="OCR 辨識舊車主姓名"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="old_owner_same_as_owner",
            field=models.BooleanField(default=True, verbose_name="新舊車主為同一人"),
        ),
        migrations.RunPython(
            infer_existing_owner_relationship,
            migrations.RunPython.noop,
        ),
    ]
