# Generated by Django 5.1.15 on 2026-07-30 02:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_postgres_search_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS sales_order_search_trgm "
        "ON sales_salesordersearchindex "
        "USING gin (search_text gin_trgm_ops)"
    )


def drop_postgres_search_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS sales_order_search_trgm")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0019_salesorder_old_owner_ocr_id_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrderSearchIndex",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="search_index",
                        serialize=False,
                        to="sales.salesorder",
                    ),
                ),
                ("search_text", models.TextField(blank=True, verbose_name="搜尋文字")),
                (
                    "match_payload",
                    models.JSONField(
                        blank=True, default=list, verbose_name="命中欄位資料"
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單搜尋索引",
                "verbose_name_plural": "訂單搜尋索引",
            },
        ),
        migrations.CreateModel(
            name="IdOcrJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "front",
                    models.ImageField(
                        upload_to="ocr_jobs/%Y/%m/", verbose_name="證件正面"
                    ),
                ),
                (
                    "back",
                    models.ImageField(
                        upload_to="ocr_jobs/%Y/%m/", verbose_name="證件反面"
                    ),
                ),
                (
                    "photo_token",
                    models.CharField(max_length=80, verbose_name="照片版本"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排隊中"),
                            ("running", "辨識中"),
                            ("succeeded", "已完成"),
                            ("failed", "失敗"),
                            ("invalidated", "已失效"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, default=dict, verbose_name="辨識結果"),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="錯誤訊息"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="嘗試次數"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_ocr_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "status", "-created_at"],
                        name="sales_idocr_created_3969c5_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(
            create_postgres_search_index,
            reverse_code=drop_postgres_search_index,
        ),
    ]
