# Generated by Django 5.1.15 on 2026-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0022_vehicleinventoryhistory"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehiclemodel",
            name="unique_vehicle_model",
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="acquisition_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="進貨成本",
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="model_code",
            field=models.CharField(blank=True, max_length=120, verbose_name="型式"),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="model_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="既有車型可暫時留空；新建車型請填西元年份。",
                null=True,
                verbose_name="年份",
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="suggested_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="建議售價",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemodel",
            constraint=models.UniqueConstraint(
                fields=("brand", "name", "model_year", "model_code"),
                name="unique_vehicle_model_variant",
            ),
        ),
    ]
