# Generated by Django 5.1.15 on 2026-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0023_remove_vehiclemodel_unique_vehicle_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="model_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("front_disc_rear_drum", "前碟後鼓"),
                    ("cbs_drum", "CBS鼓"),
                    ("cbs_disc", "CBS碟"),
                    ("abs_disc", "ABS碟"),
                    ("cbs_dual_disc", "CBS雙碟"),
                    ("abs_dual_disc", "ABS雙碟"),
                    ("disc", "碟"),
                    ("abs_triple_disc", "ABS三碟"),
                ],
                max_length=40,
                verbose_name="型式",
            ),
        ),
    ]
