# Generated by Django 5.1.15 on 2026-07-30 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0024_alter_vehiclemodel_model_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderOperationsProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "dealer_name",
                    models.CharField(blank=True, max_length=160, verbose_name="車行"),
                ),
                (
                    "actual_disbursement",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="實際撥款",
                    ),
                ),
                (
                    "vehicle_cost",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="車輛成本",
                    ),
                ),
                (
                    "registration_tax_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="領牌稅金支出",
                    ),
                ),
                (
                    "compulsory_insurance_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="強制險支出",
                    ),
                ),
                (
                    "plate_selection_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="選號支出",
                    ),
                ),
                (
                    "gift_shipping_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="贈品、運費支出",
                    ),
                ),
                (
                    "dealer_commission_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="車行傭金支出",
                    ),
                ),
                (
                    "registration_tax_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="領牌稅金收入",
                    ),
                ),
                (
                    "compulsory_insurance_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="強制險收入",
                    ),
                ),
                (
                    "agency_fee_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="代辦費收入",
                    ),
                ),
                (
                    "plate_selection_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="選號收入",
                    ),
                ),
                (
                    "installment_fee_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="分期手續費收入",
                    ),
                ),
                (
                    "card_fee_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="刷卡手續費收入",
                    ),
                ),
                (
                    "other_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="其他收入",
                    ),
                ),
                (
                    "sales_bonus",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="實銷獎勵金",
                    ),
                ),
                (
                    "promotion_subsidy",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="促銷補助金",
                    ),
                ),
                (
                    "installment_interest_subsidy",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="分期補貼息",
                    ),
                ),
                (
                    "insurance_commission",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="強制險傭金",
                    ),
                ),
                (
                    "credit_card_commission",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="信用卡傭金",
                    ),
                ),
                (
                    "payment_confirmed",
                    models.BooleanField(default=False, verbose_name="確認收款"),
                ),
                (
                    "installment_transfer_confirmed",
                    models.BooleanField(default=False, verbose_name="分期公司確認匯款"),
                ),
                (
                    "invoice_date",
                    models.DateField(blank=True, null=True, verbose_name="發票日期"),
                ),
                (
                    "balance_invoice_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="尾款發票號碼"
                    ),
                ),
                (
                    "subsidy_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="補助金額",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(blank=True, max_length=120, verbose_name="銀行"),
                ),
                (
                    "remittance_account",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="匯款帳戶"
                    ),
                ),
                (
                    "subsidy_applied_on",
                    models.DateField(blank=True, null=True, verbose_name="申請日"),
                ),
                (
                    "industry_bureau_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "未送件"),
                            ("submitted", "已送件"),
                            ("supplement", "待補件"),
                            ("reviewing", "審核中"),
                            ("approved", "已核准"),
                            ("paid", "已撥款"),
                            ("not_applicable", "不適用"),
                        ],
                        default="not_submitted",
                        max_length=30,
                        verbose_name="工業局",
                    ),
                ),
                (
                    "environment_ministry_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "未送件"),
                            ("submitted", "已送件"),
                            ("supplement", "待補件"),
                            ("reviewing", "審核中"),
                            ("approved", "已核准"),
                            ("paid", "已撥款"),
                            ("not_applicable", "不適用"),
                        ],
                        default="not_submitted",
                        max_length=30,
                        verbose_name="環境部",
                    ),
                ),
                (
                    "local_government_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "未送件"),
                            ("submitted", "已送件"),
                            ("supplement", "待補件"),
                            ("reviewing", "審核中"),
                            ("approved", "已核准"),
                            ("paid", "已撥款"),
                            ("not_applicable", "不適用"),
                        ],
                        default="not_submitted",
                        max_length=30,
                        verbose_name="縣市政府",
                    ),
                ),
                (
                    "old_vehicle_engine_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="舊車引擎號碼"
                    ),
                ),
                (
                    "old_vehicle_brand",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="舊車廠牌"
                    ),
                ),
                (
                    "old_vehicle_displacement_cc",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="舊車排氣量"
                    ),
                ),
                (
                    "old_vehicle_manufactured_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="舊車出廠日期"
                    ),
                ),
                (
                    "scrapped_on",
                    models.DateField(blank=True, null=True, verbose_name="報廢日期"),
                ),
                (
                    "recycled_on",
                    models.DateField(blank=True, null=True, verbose_name="回收日期"),
                ),
                (
                    "vehicle_control_account",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="車控帳號"
                    ),
                ),
                (
                    "vehicle_control_password_encrypted",
                    models.TextField(blank=True, verbose_name="車控密碼（加密）"),
                ),
                (
                    "battery_plan",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="電池合約方案"
                    ),
                ),
                (
                    "battery_activated_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="電池合約啟用日期"
                    ),
                ),
                (
                    "battery_account",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="電池合約帳號"
                    ),
                ),
                (
                    "battery_password_encrypted",
                    models.TextField(blank=True, verbose_name="電池合約密碼（加密）"),
                ),
                (
                    "helmet",
                    models.CharField(blank=True, max_length=250, verbose_name="安全帽"),
                ),
                (
                    "company_gift_or_remittance",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="公司禮券、匯款"
                    ),
                ),
                (
                    "other_fulfillment",
                    models.TextField(blank=True, verbose_name="其他"),
                ),
                (
                    "platform_gift",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="平台贈品"
                    ),
                ),
                (
                    "customer_service_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="客服電話"
                    ),
                ),
                (
                    "installment_info",
                    models.TextField(blank=True, verbose_name="分期資訊"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="最後更新人員"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單營運資料",
                "verbose_name_plural": "訂單營運資料",
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "item_name",
                    models.CharField(max_length=160, verbose_name="收款項目"),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="應收金額",
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="實收金額",
                    ),
                ),
                (
                    "received_on",
                    models.DateField(blank=True, null=True, verbose_name="收款日期"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="付款方式"
                    ),
                ),
                (
                    "receiving_account",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="收款帳戶"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="已確認"),
                ),
                (
                    "confirmed_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="確認人員"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認時間"
                    ),
                ),
                (
                    "proof",
                    models.FileField(
                        blank=True,
                        upload_to="orders/payments/%Y/%m/",
                        verbose_name="匯款／收款證明",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="備註"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "收款紀錄",
                "verbose_name_plural": "收款紀錄",
                "ordering": ["received_on", "id"],
            },
        ),
    ]
