# Generated by Django 5.1.15 on 2026-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0025_orderoperationsprofile_paymentrecord"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehiclemodel",
            name="unique_vehicle_model_variant",
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="model_number",
            field=models.CharField(
                blank=True,
                help_text="原廠型號或版本代碼；既有資料可暫時留空。",
                max_length=120,
                verbose_name="型號",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclemodel",
            constraint=models.UniqueConstraint(
                fields=("brand", "name", "model_number", "model_year", "model_code"),
                name="unique_vehicle_model_variant",
            ),
        ),
    ]
