# Generated by Django 5.1.15 on 2026-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0026_remove_vehiclemodel_unique_vehicle_model_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_cost_manual",
            field=models.BooleanField(default=False, verbose_name="車輛成本已人工調整"),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="system_key",
            field=models.CharField(
                blank=True,
                help_text="空白代表人工新增的收款紀錄。",
                max_length=40,
                verbose_name="系統同步代碼",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("system_key", ""), _negated=True),
                fields=("order", "system_key"),
                name="unique_order_system_payment",
            ),
        ),
    ]
