# Generated by Django 5.1.15 on 2026-07-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0027_orderoperationsprofile_vehicle_cost_manual_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleinventory",
            options={
                "ordering": ["-received_on", "-id"],
                "verbose_name": "庫存車輛",
                "verbose_name_plural": "庫存車輛",
            },
        ),
    ]
