# Generated by Django 5.1.15 on 2026-07-30 12:09

from django.db import migrations, models


def backfill_delivery_time(apps, schema_editor):
    SalesOrder = apps.get_model("sales", "SalesOrder")
    SalesOrder.objects.filter(
        status__in=["delivered_docs_pending", "completed"],
        delivered_at__isnull=True,
    ).update(delivered_at=models.F("updated_at"), delivered_by="既有訂單回填")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0028_alter_vehicleinventory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="實際交車時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="delivered_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="交車完成人員"
            ),
        ),
        migrations.RunPython(backfill_delivery_time, migrations.RunPython.noop),
    ]
