# Generated by Django 5.1.15 on 2026-07-30 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0029_salesorder_delivered_at_salesorder_delivered_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleinventory",
            name="acquisition_cost",
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_cost_county",
            field=models.CharField(
                blank=True,
                choices=[
                    ("臺北市", "臺北市"),
                    ("新北市", "新北市"),
                    ("桃園市", "桃園市"),
                    ("臺中市", "臺中市"),
                    ("臺南市", "臺南市"),
                    ("高雄市", "高雄市"),
                    ("基隆市", "基隆市"),
                    ("新竹市", "新竹市"),
                    ("嘉義市", "嘉義市"),
                    ("新竹縣", "新竹縣"),
                    ("苗栗縣", "苗栗縣"),
                    ("彰化縣", "彰化縣"),
                    ("南投縣", "南投縣"),
                    ("雲林縣", "雲林縣"),
                    ("嘉義縣", "嘉義縣"),
                    ("屏東縣", "屏東縣"),
                    ("宜蘭縣", "宜蘭縣"),
                    ("花蓮縣", "花蓮縣"),
                    ("臺東縣", "臺東縣"),
                    ("澎湖縣", "澎湖縣"),
                    ("金門縣", "金門縣"),
                    ("連江縣", "連江縣"),
                ],
                max_length=10,
                verbose_name="成本認列縣市",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_cost_locked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="成本鎖定時間"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_cost_locked_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="成本鎖定人員"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_cost_registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="成本認列領牌日"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_county",
            field=models.CharField(
                blank=True,
                choices=[
                    ("臺北市", "臺北市"),
                    ("新北市", "新北市"),
                    ("桃園市", "桃園市"),
                    ("臺中市", "臺中市"),
                    ("臺南市", "臺南市"),
                    ("高雄市", "高雄市"),
                    ("基隆市", "基隆市"),
                    ("新竹市", "新竹市"),
                    ("嘉義市", "嘉義市"),
                    ("新竹縣", "新竹縣"),
                    ("苗栗縣", "苗栗縣"),
                    ("彰化縣", "彰化縣"),
                    ("南投縣", "南投縣"),
                    ("雲林縣", "雲林縣"),
                    ("嘉義縣", "嘉義縣"),
                    ("屏東縣", "屏東縣"),
                    ("宜蘭縣", "宜蘭縣"),
                    ("花蓮縣", "花蓮縣"),
                    ("臺東縣", "臺東縣"),
                    ("澎湖縣", "澎湖縣"),
                    ("金門縣", "金門縣"),
                    ("連江縣", "連江縣"),
                ],
                max_length=10,
                verbose_name="領牌縣市",
            ),
        ),
        migrations.CreateModel(
            name="VehicleSettlementCostRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "registration_county",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("臺北市", "臺北市"),
                            ("新北市", "新北市"),
                            ("桃園市", "桃園市"),
                            ("臺中市", "臺中市"),
                            ("臺南市", "臺南市"),
                            ("高雄市", "高雄市"),
                            ("基隆市", "基隆市"),
                            ("新竹市", "新竹市"),
                            ("嘉義市", "嘉義市"),
                            ("新竹縣", "新竹縣"),
                            ("苗栗縣", "苗栗縣"),
                            ("彰化縣", "彰化縣"),
                            ("南投縣", "南投縣"),
                            ("雲林縣", "雲林縣"),
                            ("嘉義縣", "嘉義縣"),
                            ("屏東縣", "屏東縣"),
                            ("宜蘭縣", "宜蘭縣"),
                            ("花蓮縣", "花蓮縣"),
                            ("臺東縣", "臺東縣"),
                            ("澎湖縣", "澎湖縣"),
                            ("金門縣", "金門縣"),
                            ("連江縣", "連江縣"),
                        ],
                        help_text="留空代表全國預設；有指定縣市的規則會優先套用。",
                        max_length=10,
                        verbose_name="領牌縣市",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="代銷結算成本",
                    ),
                ),
                (
                    "announced_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="公告日期"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="生效日期")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="可留空；建立下一版本時，系統會依生效日選用最新規則。",
                        null=True,
                        verbose_name="結束日期",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_cost_rules",
                        to="sales.vehiclemodel",
                        verbose_name="車型",
                    ),
                ),
            ],
            options={
                "verbose_name": "代銷結算成本規則",
                "verbose_name_plural": "代銷結算成本規則",
                "ordering": [
                    "vehicle_model",
                    "registration_county",
                    "-effective_from",
                    "-id",
                ],
            },
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_cost_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_snapshots",
                to="sales.vehiclesettlementcostrule",
                verbose_name="套用成本規則",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclesettlementcostrule",
            index=models.Index(
                fields=["vehicle_model", "registration_county", "effective_from"],
                name="settlement_cost_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclesettlementcostrule",
            constraint=models.UniqueConstraint(
                fields=("vehicle_model", "registration_county", "effective_from"),
                name="unique_settlement_cost_rule_start",
            ),
        ),
    ]
