# Generated by Django 5.1.15 on 2026-07-31 05:14

from django.db import migrations, models


def protect_existing_manual_expenses(apps, schema_editor):
    profile_model = apps.get_model("sales", "OrderOperationsProfile")
    expense_fields = (
        "registration_tax_expense",
        "compulsory_insurance_expense",
        "plate_selection_expense",
    )
    for profile in profile_model.objects.all().iterator():
        protected = [
            field_name
            for field_name in expense_fields
            if getattr(profile, field_name)
        ]
        if protected:
            profile.manual_financial_fields = protected
            profile.save(update_fields=["manual_financial_fields"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0030_remove_vehicleinventory_acquisition_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="manual_financial_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="記錄不應再被訂單同步覆蓋的收支欄位。",
                verbose_name="已人工調整財務欄位",
            ),
        ),
        migrations.RunPython(
            protect_existing_manual_expenses,
            migrations.RunPython.noop,
        ),
    ]
