# Generated by Django 5.1.15 on 2026-07-31 06:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def protect_existing_incentive_snapshots(apps, schema_editor):
    profile_model = apps.get_model("sales", "OrderOperationsProfile")
    incentive_fields = (
        "sales_bonus",
        "promotion_subsidy",
        "installment_interest_subsidy",
    )
    profiles = profile_model.objects.select_related("order").all().iterator()
    for profile in profiles:
        protected = set(profile.manual_financial_fields or [])
        protected.update(
            field_name
            for field_name in incentive_fields
            if getattr(profile, field_name)
        )
        update_fields = []
        if sorted(protected) != sorted(profile.manual_financial_fields or []):
            profile.manual_financial_fields = sorted(protected)
            update_fields.append("manual_financial_fields")
        if profile.order.registration_completed_at:
            profile.incentive_registration_date = profile.order.registration_date
            profile.incentive_locked_at = profile.order.registration_completed_at
            profile.incentive_locked_by = profile.order.registration_completed_by
            update_fields.extend(
                [
                    "incentive_registration_date",
                    "incentive_locked_at",
                    "incentive_locked_by",
                ]
            )
        if update_fields:
            profile.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0031_orderoperationsprofile_manual_financial_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="incentive_locked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="獎勵補助鎖定時間"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="incentive_locked_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="獎勵補助鎖定人員"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="incentive_registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="獎勵補助認列領牌日"
            ),
        ),
        migrations.CreateModel(
            name="VehicleIncentiveRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "sales_bonus",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="實銷獎勵金",
                    ),
                ),
                (
                    "promotion_subsidy",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="促銷補助金",
                    ),
                ),
                (
                    "installment_interest_subsidy",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="分期補貼息",
                    ),
                ),
                (
                    "installment_disbursement_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="分期訂單以車款售價乘上此比例計算實際撥款。",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="分期撥款比例（%）",
                    ),
                ),
                (
                    "announced_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="公告日期"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="生效日期")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="可留空，代表持續有效；有較新版本時會優先採用新版本。",
                        null=True,
                        verbose_name="結束日期",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_rules",
                        to="sales.vehiclemodel",
                        verbose_name="車型",
                    ),
                ),
            ],
            options={
                "verbose_name": "車型獎勵補助規則",
                "verbose_name_plural": "車型獎勵補助規則",
                "ordering": ["vehicle_model", "-effective_from", "-id"],
            },
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="incentive_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_snapshots",
                to="sales.vehicleincentiverule",
                verbose_name="套用獎勵補助版本",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleincentiverule",
            index=models.Index(
                fields=["vehicle_model", "effective_from"], name="incentive_rule_lookup"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleincentiverule",
            constraint=models.UniqueConstraint(
                fields=("vehicle_model", "effective_from"),
                name="unique_incentive_rule_start",
            ),
        ),
        migrations.RunPython(
            protect_existing_incentive_snapshots,
            migrations.RunPython.noop,
        ),
    ]
