# Generated by Django 5.1.15 on 2026-07-31 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_used_legacy_rates(apps, schema_editor):
    profile_model = apps.get_model("sales", "OrderOperationsProfile")
    rate_model = apps.get_model("sales", "VehicleIncentiveInstallmentRate")
    profiles = profile_model.objects.select_related("order", "incentive_rule").iterator()
    for profile in profiles:
        rule = profile.incentive_rule
        periods = profile.order.installment_periods
        if not rule or rule.installment_disbursement_rate is None or not periods:
            continue
        rate, _created = rate_model.objects.get_or_create(
            incentive_rule_id=rule.pk,
            periods=periods,
            defaults={"rate": rule.installment_disbursement_rate},
        )
        profile.incentive_installment_rate_rule_id = rate.pk
        profile.incentive_installment_periods = periods
        profile.incentive_installment_rate = rate.rate
        profile.save(
            update_fields=[
                "incentive_installment_rate_rule",
                "incentive_installment_periods",
                "incentive_installment_rate",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0032_orderoperationsprofile_incentive_locked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="incentive_installment_periods",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="撥款認列分期期數"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="incentive_installment_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="撥款認列比例（%）",
            ),
        ),
        migrations.CreateModel(
            name="VehicleIncentiveInstallmentRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "periods",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="分期期數",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="實際撥款比例（%）",
                    ),
                ),
                (
                    "incentive_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_rates",
                        to="sales.vehicleincentiverule",
                        verbose_name="獎勵補助版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "分期期數撥款比例",
                "verbose_name_plural": "分期期數撥款比例",
                "ordering": ["periods", "id"],
            },
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="incentive_installment_rate_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_snapshots",
                to="sales.vehicleincentiveinstallmentrate",
                verbose_name="套用分期期數比例",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicleincentiveinstallmentrate",
            constraint=models.UniqueConstraint(
                fields=("incentive_rule", "periods"),
                name="unique_incentive_installment_periods",
            ),
        ),
        migrations.RunPython(
            migrate_used_legacy_rates,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="vehicleincentiverule",
            name="installment_disbursement_rate",
        ),
    ]
