# Generated by Django 5.1.15 on 2026-08-04 12:45

import re

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def populate_normalized_identifiers(apps, schema_editor):
    VehicleInventory = apps.get_model("sales", "VehicleInventory")
    seen_engine = set()
    seen_frame = set()
    for vehicle in VehicleInventory.objects.order_by("pk").iterator():
        engine = re.sub(r"[\s-]+", "", vehicle.engine_number or "").upper() or None
        frame = re.sub(r"[\s-]+", "", vehicle.frame_number or "").upper() or None
        # 舊資料若已重複，保留最早一筆的比對鍵，其餘留待人工清理；
        # 不因歷史髒資料中斷整個正式環境 migration。
        if engine in seen_engine:
            engine = None
        if frame in seen_frame:
            frame = None
        if engine:
            seen_engine.add(engine)
        if frame:
            seen_frame.add(frame)
        VehicleInventory.objects.filter(pk=vehicle.pk).update(
            normalized_engine_number=engine,
            normalized_frame_number=frame,
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales",
            "0033_remove_vehicleincentiverule_installment_disbursement_rate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinventory",
            name="manufactured_year_month",
            field=models.CharField(
                blank=True,
                help_text="供車輛年份顯示與庫存先進先出判斷。",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="請使用 YYYY/MM，例如 2026/08。",
                        regex="^\\d{4}/(0[1-9]|1[0-2])$",
                    )
                ],
                verbose_name="出廠年月",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="normalized_engine_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=80,
                null=True,
                verbose_name="標準化引擎號碼",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="normalized_frame_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=80,
                null=True,
                verbose_name="標準化車身號碼",
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="horsepower_hp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="電動車或微型電動二輪車選填；不會由 kW 自動換算。",
                max_digits=8,
                null=True,
                verbose_name="馬力（HP）",
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="motor_power_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="電動車或微型電動二輪車選填；不會自動換算馬力。",
                max_digits=8,
                null=True,
                verbose_name="馬達功率（kW）",
            ),
        ),
        migrations.RunPython(
            populate_normalized_identifiers,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="vehicleinventory",
            name="normalized_engine_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="標準化引擎號碼",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinventory",
            name="normalized_frame_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=80,
                null=True,
                unique=True,
                verbose_name="標準化車身號碼",
            ),
        ),
        migrations.CreateModel(
            name="VehiclePriceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "suggested_retail_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="公司建議售價",
                    ),
                ),
                (
                    "cash_price_including_registration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="現金含牌險價",
                    ),
                ),
                (
                    "cash_price_excluding_registration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="現金未含牌險價",
                    ),
                ),
                (
                    "cash_purchase_bonus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="現金購車金",
                    ),
                ),
                (
                    "announced_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="公告日期"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="生效日期")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "source_note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="來源文件／說明"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_versions",
                        to="sales.vehiclemodel",
                        verbose_name="車型",
                    ),
                ),
            ],
            options={
                "verbose_name": "車型價格版本",
                "verbose_name_plural": "車型價格版本",
                "ordering": ["vehicle_model", "-effective_from", "-id"],
                "indexes": [
                    models.Index(
                        fields=["vehicle_model", "effective_from"],
                        name="vehicle_price_lookup",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle_model", "effective_from"),
                        name="unique_vehicle_price_version_start",
                    )
                ],
            },
        ),
    ]
