# Generated by Django 5.1.15 on 2026-08-04 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0034_vehicleinventory_manufactured_year_month_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderoperationsprofile",
            old_name="gift_shipping_expense",
            new_name="gift_expense",
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="gift_expense",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="贈品支出",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="card_fee_expense",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="銀行刷卡手續費支出",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="scrap_agency_income",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="報廢代辦收入"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="scrap_vehicle_income",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="報廢車收入"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="shipping_expense",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="運費支出"
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="bank_card_fee",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="銀行實扣手續費",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="card_fee_charged",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="向客戶收取手續費",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="card_principal",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="刷卡本金",
            ),
        ),
    ]
