# Generated by Django 5.1.15 on 2026-08-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0035_remove_orderoperationsprofile_gift_shipping_expense_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="price_snapshot",
            field=models.JSONField(
                blank=True, default=dict, editable=False, verbose_name="訂單售價快照"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="price_snapshot_locked_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="售價快照保存時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="price_version",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="sales.vehiclepriceversion",
                verbose_name="訂單售價版本",
            ),
        ),
    ]
