# Generated by Django 5.1.15 on 2026-08-05 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0036_sales_order_price_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="配件名稱"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="配件售價",
                    ),
                ),
                (
                    "labor_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="安裝工資",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="無法固定維護時可留空；此欄位不會顯示在客戶訂單。",
                        max_digits=12,
                        null=True,
                        verbose_name="參考成本",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="內部備註"
                    ),
                ),
            ],
            options={
                "verbose_name": "配件主檔",
                "verbose_name_plural": "配件主檔",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="accessoryline",
            name="labor_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="安裝工資"
            ),
        ),
        migrations.AlterField(
            model_name="accessoryline",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="配件售價"
            ),
        ),
        migrations.AddField(
            model_name="accessoryline",
            name="accessory_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_lines",
                to="sales.accessoryproduct",
                verbose_name="配件主檔",
            ),
        ),
    ]
