# Generated by Django 5.1.15 on 2026-08-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0037_accessory_master_and_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessoryline",
            name="installed_on",
        ),
    ]
