# Generated by Django 5.1.15 on 2026-08-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0038_remove_accessory_installation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="日期"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="假日名稱")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="排除工作日計算"),
                ),
            ],
            options={
                "verbose_name": "國定假日",
                "verbose_name_plural": "國定假日",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cancellation_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="取消完成時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cancellation_completed_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="取消完成人員"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cancellation_note",
            field=models.TextField(blank=True, verbose_name="取消說明"),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=250, verbose_name="取消原因"),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cancellation_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="取消申請時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="cancellation_requested_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="取消登記人員"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="退款金額"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="refund_completed_on",
            field=models.DateField(blank=True, null=True, verbose_name="退款完成日期"),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="refund_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "現金"),
                    ("transfer", "匯款"),
                    ("card", "刷卡"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="退款方式",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="refund_proof",
            field=models.FileField(
                blank=True, upload_to="orders/refunds/%Y/%m/", verbose_name="退款證明"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="refund_reference",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="退款帳號／交易資訊"
            ),
        ),
        migrations.CreateModel(
            name="DeliveryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=160, verbose_name="實際收車人"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=30, verbose_name="收車人電話"),
                ),
                (
                    "carrier_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="託運公司"
                    ),
                ),
                (
                    "handover_location",
                    models.CharField(max_length=250, verbose_name="實際交付地點"),
                ),
                ("vehicle_condition_note", models.TextField(verbose_name="交付車況")),
                (
                    "condition_checked",
                    models.BooleanField(default=False, verbose_name="已核對車況"),
                ),
                (
                    "documents_checked",
                    models.BooleanField(default=False, verbose_name="已核對交付文件"),
                ),
                (
                    "keys_checked",
                    models.BooleanField(default=False, verbose_name="已核對鑰匙"),
                ),
                (
                    "accessories_checked",
                    models.BooleanField(default=False, verbose_name="已核對配件與贈品"),
                ),
                (
                    "payment_checked",
                    models.BooleanField(default=False, verbose_name="已核對收款狀態"),
                ),
                (
                    "damage_found",
                    models.BooleanField(default=False, verbose_name="發現刮傷或損壞"),
                ),
                (
                    "damage_note",
                    models.TextField(blank=True, verbose_name="刮傷／損壞說明"),
                ),
                (
                    "handover_photo",
                    models.ImageField(
                        blank=True,
                        upload_to="orders/delivery/%Y/%m/",
                        verbose_name="交付照片",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="交付備註")),
                (
                    "completed_by",
                    models.CharField(max_length=150, verbose_name="交付登記人員"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_record",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "交付紀錄",
                "verbose_name_plural": "交付紀錄",
            },
        ),
    ]
