# Generated by Django 5.1.15 on 2026-08-05 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0040_seed_2026_2027_business_holidays"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstallmentCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="分期公司"
                    ),
                ),
                (
                    "customer_service_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="客服電話"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                ("note", models.TextField(blank=True, verbose_name="內部備註")),
            ],
            options={
                "verbose_name": "分期公司",
                "verbose_name_plural": "分期公司",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="dealer_commission_adjustment",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="車行加減佣金快照",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="dealer_commission_base",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="車行基礎佣金快照",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="dealer_commission_locked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="車行佣金鎖定時間"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="dealer_commission_registration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="車行佣金認列領牌日"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="installment_plan_snapshot",
            field=models.JSONField(
                blank=True, default=dict, editable=False, verbose_name="分期方案快照"
            ),
        ),
        migrations.AddField(
            model_name="salessource",
            name="address",
            field=models.CharField(blank=True, max_length=250, verbose_name="地址"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="code",
            field=models.CharField(blank=True, max_length=40, verbose_name="來源代碼"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="fax",
            field=models.CharField(blank=True, max_length=50, verbose_name="傳真"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="note",
            field=models.TextField(blank=True, verbose_name="內部備註"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="電話"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="relationship_note",
            field=models.TextField(blank=True, verbose_name="年節送禮／關係備註"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="vehicle_capacity",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="可停放車輛數量"
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="base_dealer_commission",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="基礎車行佣金",
            ),
        ),
        migrations.CreateModel(
            name="DealerVolumeBonusRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="品牌")),
                ("starts_on", models.DateField(verbose_name="統計開始日")),
                ("ends_on", models.DateField(verbose_name="統計結束日")),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "dealer",
                    models.ForeignKey(
                        limit_choices_to={"source_type": "dealer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volume_bonus_rules",
                        to="sales.salessource",
                        verbose_name="合作車行",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行台數獎金規則",
                "verbose_name_plural": "車行台數獎金規則",
                "ordering": ["-starts_on", "dealer", "brand"],
            },
        ),
        migrations.CreateModel(
            name="DealerVolumeBonusSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "qualified_quantity",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="符合台數"
                    ),
                ),
                (
                    "bonus_per_vehicle",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="採用每台獎金",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="預計金額",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="實際金額",
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(blank=True, verbose_name="金額調整原因"),
                ),
                (
                    "settled_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="結算日期"
                    ),
                ),
                (
                    "settled_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="結算人員"
                    ),
                ),
                (
                    "rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement",
                        to="sales.dealervolumebonusrule",
                        verbose_name="台數獎金規則",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行台數獎金結算",
                "verbose_name_plural": "車行台數獎金結算",
                "ordering": ["-settled_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DealerVolumeBonusAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="分配金額",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealer_volume_bonus_allocations",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="sales.dealervolumebonussettlement",
                        verbose_name="台數獎金結算",
                    ),
                ),
            ],
            options={
                "verbose_name": "台數獎金逐單明細",
                "verbose_name_plural": "台數獎金逐單明細",
                "ordering": ["order__registration_date", "order_id"],
            },
        ),
        migrations.CreateModel(
            name="DealerVolumeBonusTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "minimum_quantity",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最低台數",
                    ),
                ),
                (
                    "bonus_per_vehicle",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="每台獎金",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="sales.dealervolumebonusrule",
                        verbose_name="台數獎金規則",
                    ),
                ),
            ],
            options={
                "verbose_name": "台數獎金門檻",
                "verbose_name_plural": "台數獎金門檻",
                "ordering": ["minimum_quantity"],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="installment_company_master",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="sales.installmentcompany",
                verbose_name="分期公司主檔",
            ),
        ),
        migrations.CreateModel(
            name="InstallmentPlanOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "periods",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="期數",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="每期金額",
                    ),
                ),
                (
                    "opening_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="開辦費",
                    ),
                ),
                (
                    "expected_disbursement_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="預估撥款比例（%）",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_options",
                        to="sales.installmentcompany",
                        verbose_name="分期公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "分期方案期數",
                "verbose_name_plural": "分期方案期數",
                "ordering": ["periods", "id"],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="installment_plan_option",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="sales.installmentplanoption",
                verbose_name="套用分期方案",
            ),
        ),
        migrations.CreateModel(
            name="InstallmentPlanVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "announced_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="公告日期"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="生效日期")),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="可留空，代表持續有效；訂單依訂單日期選用版本。",
                        null=True,
                        verbose_name="結束日期",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installment_plan_versions",
                        to="sales.vehiclemodel",
                        verbose_name="車型",
                    ),
                ),
            ],
            options={
                "verbose_name": "分期方案版本",
                "verbose_name_plural": "分期方案版本",
                "ordering": ["vehicle_model", "-effective_from", "-id"],
            },
        ),
        migrations.AddField(
            model_name="installmentplanoption",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="sales.installmentplanversion",
                verbose_name="分期方案版本",
            ),
        ),
        migrations.CreateModel(
            name="SalesSourceBrandPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="品牌")),
                (
                    "cooperates",
                    models.BooleanField(default=True, verbose_name="有配合"),
                ),
                (
                    "commission_adjustment",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="加碼請填正數，減少請填負數。",
                        max_digits=12,
                        verbose_name="佣金加減額",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="生效日期"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="品牌合作備註"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_policies",
                        to="sales.salessource",
                        verbose_name="來源",
                    ),
                ),
            ],
            options={
                "verbose_name": "通路品牌合作規則",
                "verbose_name_plural": "通路品牌合作規則",
                "ordering": ["source", "brand", "-effective_from"],
            },
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="dealer_commission_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_snapshots",
                to="sales.salessourcebrandpolicy",
                verbose_name="套用車行品牌規則",
            ),
        ),
        migrations.CreateModel(
            name="SalesSourceContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="姓名／窗口")),
                (
                    "relationship",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="關係／職務"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="電話"),
                ),
                (
                    "extension",
                    models.CharField(blank=True, max_length=20, verbose_name="分機"),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=50, verbose_name="手機"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="備註"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="sales.salessource",
                        verbose_name="來源",
                    ),
                ),
            ],
            options={
                "verbose_name": "通路聯絡窗口",
                "verbose_name_plural": "通路聯絡窗口",
                "ordering": ["source", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dealervolumebonusrule",
            constraint=models.UniqueConstraint(
                fields=("dealer", "brand", "starts_on", "ends_on"),
                name="unique_dealer_volume_bonus_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="dealervolumebonusallocation",
            constraint=models.UniqueConstraint(
                fields=("settlement", "order"),
                name="unique_volume_bonus_settlement_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="dealervolumebonustier",
            constraint=models.UniqueConstraint(
                fields=("rule", "minimum_quantity"),
                name="unique_volume_bonus_tier_quantity",
            ),
        ),
        migrations.AddIndex(
            model_name="installmentplanversion",
            index=models.Index(
                fields=["vehicle_model", "effective_from"],
                name="installment_plan_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplanversion",
            constraint=models.UniqueConstraint(
                fields=("vehicle_model", "effective_from"),
                name="unique_installment_plan_version_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="installmentplanoption",
            constraint=models.UniqueConstraint(
                fields=("version", "periods"), name="unique_installment_plan_periods"
            ),
        ),
        migrations.AddIndex(
            model_name="salessourcebrandpolicy",
            index=models.Index(
                fields=["source", "brand", "effective_from"],
                name="source_brand_policy_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="salessourcebrandpolicy",
            constraint=models.UniqueConstraint(
                fields=("source", "brand", "effective_from"),
                name="unique_source_brand_policy_start",
            ),
        ),
    ]
