# Generated by Django 5.1.15 on 2026-08-05 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0041_channel_finance_masters"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerVolumeBonusAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "previous_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="調整前金額"
                    ),
                ),
                (
                    "revised_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="調整後金額"
                    ),
                ),
                ("reason", models.TextField(verbose_name="調整原因")),
                (
                    "adjusted_by",
                    models.CharField(max_length=150, verbose_name="調整人員"),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="sales.dealervolumebonussettlement",
                        verbose_name="台數獎金結算",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行台數獎金調整紀錄",
                "verbose_name_plural": "車行台數獎金調整紀錄",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
