# Generated by Django 5.1.15 on 2026-08-05 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0042_dealervolumebonusadjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyImportBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("operations", "車輛進銷貨庫存表"),
                            ("channels", "車行／網路平台名冊"),
                        ],
                        max_length=30,
                        verbose_name="匯入類型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "待確認"),
                            ("completed", "已匯入"),
                            ("failed", "處理失敗"),
                        ],
                        default="preview",
                        max_length=20,
                        verbose_name="批次狀態",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="imports/%Y/%m/", verbose_name="來源檔案"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始檔名"),
                ),
                (
                    "file_sha256",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="SHA-256"
                    ),
                ),
                ("file_size", models.PositiveBigIntegerField(verbose_name="檔案大小")),
                (
                    "source_sheets",
                    models.JSONField(default=list, verbose_name="來源工作表"),
                ),
                (
                    "preview_summary",
                    models.JSONField(default=dict, verbose_name="預覽摘要"),
                ),
                (
                    "result_summary",
                    models.JSONField(default=dict, verbose_name="匯入結果"),
                ),
                (
                    "uploaded_by",
                    models.CharField(max_length=150, verbose_name="上傳人員"),
                ),
                (
                    "confirmed_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="確認人員"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確認時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "歷史資料匯入批次",
                "verbose_name_plural": "歷史資料匯入批次",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegacyImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("sheet_name", models.CharField(max_length=120, verbose_name="工作表")),
                ("source_row", models.PositiveIntegerField(verbose_name="來源列號")),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="內容指紋"
                    ),
                ),
                (
                    "natural_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, verbose_name="比對鍵"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "新增"),
                            ("update", "更新"),
                            ("skip", "略過"),
                            ("conflict", "衝突"),
                            ("error", "錯誤"),
                        ],
                        max_length=20,
                        verbose_name="預計動作",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(default=dict, verbose_name="來源原始資料"),
                ),
                (
                    "mapped_data",
                    models.JSONField(default=dict, verbose_name="欄位映射結果"),
                ),
                ("messages", models.JSONField(default=list, verbose_name="檢核訊息")),
                (
                    "committed_model",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="建立資料類型"
                    ),
                ),
                (
                    "committed_pk",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="建立資料編號"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="sales.legacyimportbatch",
                        verbose_name="匯入批次",
                    ),
                ),
            ],
            options={
                "verbose_name": "歷史資料匯入列",
                "verbose_name_plural": "歷史資料匯入列",
                "ordering": ["sheet_name", "source_row"],
            },
        ),
        migrations.CreateModel(
            name="LegacySalesSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "historical_received_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="歷史收款價",
                    ),
                ),
                (
                    "cash_received",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="歷史現金收款",
                    ),
                ),
                (
                    "card_received",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="歷史刷卡收款",
                    ),
                ),
                (
                    "sales_category",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="銷售方案分類"
                    ),
                ),
                (
                    "raw_financials",
                    models.JSONField(default=dict, verbose_name="歷史收支原值"),
                ),
                (
                    "import_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_snapshot",
                        to="sales.legacyimportrow",
                        verbose_name="匯入來源列",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_snapshot",
                        to="sales.salesorder",
                        verbose_name="歷史訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "歷史銷貨快照",
                "verbose_name_plural": "歷史銷貨快照",
            },
        ),
        migrations.AddConstraint(
            model_name="legacyimportrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "sheet_name", "source_row"),
                name="unique_legacy_import_source_row",
            ),
        ),
    ]
