# Generated by Django 5.1.15 on 2026-08-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0043_legacyimportbatch_legacyimportrow_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("industry", "工業局"),
                            ("environment", "環境部"),
                            ("local", "地方政府"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="類別",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=160, verbose_name="補助項目"),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="預計金額",
                    ),
                ),
                (
                    "applied_on",
                    models.DateField(blank=True, null=True, verbose_name="申請日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "未申請"),
                            ("submitted", "已送出申請"),
                            ("completed", "已申請完成"),
                        ],
                        default="not_submitted",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="備註"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidy_items",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "補助項目",
                "verbose_name_plural": "補助項目",
                "ordering": ["category", "id"],
            },
        ),
    ]
