# Generated by Django 5.1.15 on 2026-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0044_subsidyitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandRegistrationFeeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="品牌")),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("formula", "公式計算"),
                            ("fixed", "固定整包金額"),
                            ("manual", "人工輸入"),
                        ],
                        max_length=20,
                        verbose_name="計算方式",
                    ),
                ),
                (
                    "min_cc",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="最低排氣量"
                    ),
                ),
                (
                    "max_cc",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="最高排氣量"
                    ),
                ),
                (
                    "fixed_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="固定牌險總額",
                    ),
                ),
                (
                    "insurance_period_years",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="強制險年期"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="生效日期")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                ("note", models.TextField(blank=True, verbose_name="備註")),
            ],
            options={
                "verbose_name": "品牌牌險規則",
                "verbose_name_plural": "品牌牌險規則",
                "ordering": ["brand", "min_cc", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["brand", "effective_from"], name="brand_reg_fee_lookup"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "min_cc", "max_cc", "effective_from"),
                        name="unique_brand_registration_fee_version",
                    )
                ],
            },
        ),
    ]
