# Generated by Django 5.1.15 on 2026-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0045_brandregistrationfeerule"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="registration_fee_variance_confirmed_actual_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="已確認實際牌險金額",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_fee_variance_confirmed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="牌險差額確認時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_fee_variance_confirmed_by",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=150,
                verbose_name="牌險差額確認人員",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_fee_variance_confirmed_calculated_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="已確認系統牌險金額",
            ),
        ),
    ]
