# Generated by Django 5.1.15 on 2026-08-05 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales",
            "0046_salesorder_registration_fee_variance_confirmed_actual_total_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionedPrintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="範本名稱")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("envelope", "信封"),
                            ("submission", "報件單"),
                            ("tax_declaration", "減徵貨物稅聲明書"),
                            ("tax_consent", "退稅同意書"),
                            ("eready_checklist", "eReady 交車點檢表"),
                        ],
                        max_length=30,
                        verbose_name="文件類型",
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, verbose_name="版本"),
                ),
                (
                    "paper_size",
                    models.CharField(
                        choices=[("a4", "A4"), ("a5", "A5"), ("custom", "自訂尺寸")],
                        default="a4",
                        max_length=20,
                        verbose_name="紙張",
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[("portrait", "直式"), ("landscape", "橫式")],
                        default="portrait",
                        max_length=20,
                        verbose_name="方向",
                    ),
                ),
                (
                    "width_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="自訂寬度 mm",
                    ),
                ),
                (
                    "height_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="自訂高度 mm",
                    ),
                ),
                (
                    "background_file",
                    models.FileField(
                        blank=True,
                        upload_to="print_templates/%Y/%m/",
                        verbose_name="背景檔案",
                    ),
                ),
                (
                    "printer_offset_x_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="印表機水平偏移 mm",
                    ),
                ),
                (
                    "printer_offset_y_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="印表機垂直偏移 mm",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                ("note", models.TextField(blank=True, verbose_name="備註")),
            ],
            options={
                "verbose_name": "定位列印範本",
                "verbose_name_plural": "定位列印範本",
                "ordering": ["document_type", "-version", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "version"),
                        name="unique_positioned_template_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PositionedPrintField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("field_key", models.CharField(max_length=80, verbose_name="資料欄位")),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="內部標籤"
                    ),
                ),
                (
                    "x_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=7,
                        verbose_name="左側位置 mm",
                    ),
                ),
                (
                    "y_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=7,
                        verbose_name="頂端位置 mm",
                    ),
                ),
                (
                    "width_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        max_digits=7,
                        verbose_name="欄位寬度 mm",
                    ),
                ),
                (
                    "font_size",
                    models.DecimalField(
                        decimal_places=1, default=10, max_digits=5, verbose_name="字級"
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("left", "靠左"),
                            ("center", "置中"),
                            ("right", "靠右"),
                        ],
                        default="left",
                        max_length=10,
                        verbose_name="對齊",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="前置文字"
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="後置文字"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="顯示")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="sales.positionedprinttemplate",
                        verbose_name="範本",
                    ),
                ),
            ],
            options={
                "verbose_name": "定位列印欄位",
                "verbose_name_plural": "定位列印欄位",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
