# Generated by Django 5.1.15 on 2026-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0047_positionedprinttemplate_positionedprintfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="approved_discount_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="內部核准折扣",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_decided_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="折扣確認時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_decided_by",
            field=models.CharField(
                blank=True, editable=False, max_length=150, verbose_name="折扣確認人"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_decision_note",
            field=models.CharField(
                blank=True, editable=False, max_length=250, verbose_name="折扣確認備註"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_reason",
            field=models.CharField(
                blank=True, editable=False, max_length=250, verbose_name="折扣原因"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_requested_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="申請折扣金額",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_requested_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="折扣申請時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_requested_by",
            field=models.CharField(
                blank=True, editable=False, max_length=150, verbose_name="折扣申請人"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "未申請"),
                    ("pending", "待確認"),
                    ("approved", "已核准"),
                    ("rejected", "未採用"),
                ],
                editable=False,
                max_length=20,
                verbose_name="折扣狀態",
            ),
        ),
    ]
