# Generated by Django 5.1.15 on 2026-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0048_salesorder_approved_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paymentrecord",
            index=models.Index(
                fields=["order", "confirmed"], name="payment_order_confirmed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["order_date"], name="sales_order_date_idx"),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["registration_date"], name="sales_registration_date_idx"
            ),
        ),
    ]
