# Generated by Django 5.2.16 on 2026-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0052_legacy_import_correction_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacysalessnapshot",
            name="vehicle_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=80,
                verbose_name="歷史引擎／車身號碼",
            ),
        ),
    ]
