# Generated by Django 5.2.16 on 2026-08-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0053_legacysalessnapshot_vehicle_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyImportMasterMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "source_value",
                    models.CharField(max_length=200, verbose_name="Excel 原始名稱"),
                ),
                (
                    "normalized_source_value",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="標準化名稱"
                    ),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[("vehicle_model", "車型"), ("sales_source", "通路")],
                        max_length=30,
                        verbose_name="主檔類型",
                    ),
                ),
                (
                    "ignored",
                    models.BooleanField(
                        default=False,
                        help_text="不建立或對應主檔；匯入時仍保留 Excel 原始文字。",
                        verbose_name="保留歷史文字",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="處理說明"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(max_length=150, verbose_name="最後處理人員"),
                ),
                (
                    "sales_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_import_mappings",
                        to="sales.salessource",
                        verbose_name="對應通路",
                    ),
                ),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_import_mappings",
                        to="sales.vehiclemodel",
                        verbose_name="對應車型",
                    ),
                ),
            ],
            options={
                "verbose_name": "歷史匯入主檔對應",
                "verbose_name_plural": "歷史匯入主檔對應",
                "ordering": ["mapping_type", "source_value"],
                "indexes": [
                    models.Index(
                        fields=["mapping_type", "normalized_source_value"],
                        name="legacy_master_mapping_lookup",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mapping_type", "normalized_source_value"),
                        name="unique_legacy_master_mapping",
                    )
                ],
            },
        ),
    ]
