# Generated by Django 5.2.16 on 2026-08-11 04:56

import django.db.models.deletion
from django.db import migrations, models


def seed_categories_and_transaction_types(apps, schema_editor):
    SalesSourceCategory = apps.get_model("sales", "SalesSourceCategory")
    SalesSource = apps.get_model("sales", "SalesSource")
    SalesOrder = apps.get_model("sales", "SalesOrder")
    LegacySalesSnapshot = apps.get_model("sales", "LegacySalesSnapshot")
    OrderOperationsProfile = apps.get_model("sales", "OrderOperationsProfile")

    categories = {}
    for name, behavior in (
        ("合作車行", "dealer"),
        ("網路平台", "platform"),
        ("本店員工", "store"),
        ("其他來源", "store"),
    ):
        categories[behavior if behavior != "store" else name] = (
            SalesSourceCategory.objects.create(
                name=name,
                system_behavior=behavior,
            )
        )

    SalesSource.objects.filter(source_type="dealer").update(
        category=categories["dealer"]
    )
    SalesSource.objects.filter(source_type="platform").update(
        category=categories["platform"]
    )
    SalesSource.objects.filter(source_type="store").update(
        category=categories["其他來源"]
    )

    SalesOrder.objects.filter(vehicle_category="used").update(
        transaction_type="used"
    )
    legacy_labels = dict(
        LegacySalesSnapshot.objects.values_list("order_id", "sales_category")
    )
    operation_labels = dict(
        OrderOperationsProfile.objects.values_list("order_id", "dealer_name")
    )
    updates = []
    for order in SalesOrder.objects.exclude(vehicle_category="used"):
        label = f"{legacy_labels.get(order.pk, '')} {operation_labels.get(order.pk, '')}"
        if "試乘" in label:
            order.transaction_type = "test_ride"
        elif "中獎" in label:
            order.transaction_type = "prize"
        elif "領牌車" in label:
            order.transaction_type = "registered"
        else:
            continue
        updates.append(order)
    if updates:
        SalesOrder.objects.bulk_update(updates, ["transaction_type"], batch_size=500)


def reverse_seed(apps, schema_editor):
    SalesSource = apps.get_model("sales", "SalesSource")
    SalesSource.objects.update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0054_legacyimportmastermapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="分類名稱"
                    ),
                ),
                (
                    "system_behavior",
                    models.CharField(
                        choices=[
                            ("store", "本店來源"),
                            ("dealer", "合作車行"),
                            ("platform", "網路平台"),
                        ],
                        default="store",
                        help_text="決定是否套用車行傭金、平台對帳或視為本店來源。",
                        max_length=20,
                        verbose_name="系統處理方式",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="內部備註"
                    ),
                ),
            ],
            options={
                "verbose_name": "通路分類",
                "verbose_name_plural": "通路分類",
                "ordering": ["system_behavior", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("regular_new", "一般新車"),
                    ("registered", "領牌車"),
                    ("test_ride", "試乘車"),
                    ("prize", "中獎車"),
                    ("used", "中古車交易"),
                    ("other", "其他"),
                ],
                db_index=True,
                default="regular_new",
                help_text="用來區分一般新車、領牌車、試乘車、中獎車或中古車交易。",
                max_length=20,
                verbose_name="交易類型",
            ),
        ),
        migrations.AlterField(
            model_name="salessource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("store", "本店來源"),
                    ("dealer", "合作車行"),
                    ("platform", "網路平台"),
                ],
                max_length=20,
                verbose_name="系統處理方式",
            ),
        ),
        migrations.AddField(
            model_name="salessource",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                to="sales.salessourcecategory",
                verbose_name="通路分類",
            ),
        ),
        migrations.RunPython(seed_categories_and_transaction_types, reverse_seed),
    ]
