# Generated by Django 5.2.16 on 2026-08-13 06:31

from django.db import migrations, models


def migrate_price_values(apps, schema_editor):
    VehiclePriceVersion = apps.get_model("sales", "VehiclePriceVersion")
    for version in VehiclePriceVersion.objects.all().iterator():
        version.suggested_price_including_registration = version.suggested_retail_price
        version.cash_price = (
            version.cash_price_excluding_registration
            if version.cash_price_excluding_registration is not None
            else version.cash_price_including_registration
        )
        version.save(
            update_fields=[
                "suggested_price_including_registration",
                "cash_price",
            ]
        )


def restore_legacy_price_values(apps, schema_editor):
    VehiclePriceVersion = apps.get_model("sales", "VehiclePriceVersion")
    for version in VehiclePriceVersion.objects.all().iterator():
        version.suggested_retail_price = version.suggested_price_including_registration
        version.cash_price_excluding_registration = version.cash_price
        version.save(
            update_fields=[
                "suggested_retail_price",
                "cash_price_excluding_registration",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0058_vehicle_price_single_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="brandregistrationfeerule",
            name="unique_brand_registration_fee_version",
        ),
        migrations.RemoveIndex(
            model_name="brandregistrationfeerule",
            name="brand_reg_fee_lookup",
        ),
        migrations.AddField(
            model_name="brandregistrationfeerule",
            name="electric_registration_class",
            field=models.CharField(
                blank=True,
                choices=[("light", "輕型電動機車"), ("heavy", "重型電動機車")],
                max_length=20,
                verbose_name="電動車領牌級別",
            ),
        ),
        migrations.AddField(
            model_name="brandregistrationfeerule",
            name="energy_type",
            field=models.CharField(
                choices=[
                    ("gas", "油車"),
                    ("electric", "電動車"),
                    ("micro_electric", "微型電動二輪車"),
                ],
                default="gas",
                max_length=20,
                verbose_name="能源別",
            ),
        ),
        migrations.AddField(
            model_name="brandregistrationfeerule",
            name="fixed_compulsory_insurance_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="固定強制險"
            ),
        ),
        migrations.AddField(
            model_name="brandregistrationfeerule",
            name="fixed_registration_fee",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="固定領牌規費"
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="electric_registration_class",
            field=models.CharField(
                blank=True,
                choices=[("light", "輕型電動機車"), ("heavy", "重型電動機車")],
                help_text="僅電動車使用；請依原廠認證選擇，不會由馬達功率自動推算。",
                max_length=20,
                verbose_name="電動車領牌級別",
            ),
        ),
        migrations.AddField(
            model_name="vehiclepriceversion",
            name="cash_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="現金價",
            ),
        ),
        migrations.AddField(
            model_name="vehiclepriceversion",
            name="suggested_price_including_registration",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="建議售價（含牌險）",
            ),
        ),
        migrations.RunPython(migrate_price_values, restore_legacy_price_values),
        migrations.RemoveField(
            model_name="vehiclepriceversion",
            name="cash_price_excluding_registration",
        ),
        migrations.RemoveField(
            model_name="vehiclepriceversion",
            name="cash_price_including_registration",
        ),
        migrations.RemoveField(
            model_name="vehiclepriceversion",
            name="cash_purchase_bonus",
        ),
        migrations.RemoveField(
            model_name="vehiclepriceversion",
            name="suggested_retail_price",
        ),
        migrations.AddIndex(
            model_name="brandregistrationfeerule",
            index=models.Index(
                fields=["brand", "energy_type", "effective_from"],
                name="brand_reg_fee_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandregistrationfeerule",
            constraint=models.UniqueConstraint(
                fields=(
                    "brand",
                    "energy_type",
                    "electric_registration_class",
                    "min_cc",
                    "max_cc",
                    "effective_from",
                ),
                name="unique_brand_registration_fee_version",
            ),
        ),
    ]
