# Generated by Django 5.2.16 on 2026-08-13 10:23

import django.db.models.functions.text
from django.db import migrations, models


COMMON_BRANDS = (
    (10, "KYMCO", "光陽、光陽 Kymco"),
    (20, "SYM", "三陽、三陽 SYM"),
    (30, "YAMAHA", "山葉、山葉 Yamaha"),
    (40, "SUZUKI", "台鈴、台鈴 Suzuki、Suzuki"),
    (50, "PGO", "比雅久、比雅久 PGO"),
    (60, "Gogoro", "GOGORO、睿能、睿能 Gogoro"),
    (70, "eMOVING", "EMOVING、中華 eMoving"),
    (80, "AEON", "宏佳騰、宏佳騰 Aeon、AEON MOTOR"),
    (90, "THEMO", "爍魔、爍魔 THEMO"),
    (100, "Vespa", "偉士牌、VESPA"),
    (110, "HONDA", "本田、Honda"),
    (120, "Kawasaki", "川崎、KAWASAKI"),
)


def seed_and_normalize_brands(apps, schema_editor):
    VehicleBrand = apps.get_model("sales", "VehicleBrand")
    VehicleModel = apps.get_model("sales", "VehicleModel")
    SalesSourceBrandPolicy = apps.get_model("sales", "SalesSourceBrandPolicy")
    DealerVolumeBonusRule = apps.get_model("sales", "DealerVolumeBonusRule")
    BrandRegistrationFeeRule = apps.get_model("sales", "BrandRegistrationFeeRule")

    canonical_by_key = {}
    for order, name, aliases in COMMON_BRANDS:
        VehicleBrand.objects.create(
            name=name,
            aliases=aliases,
            display_order=order,
            active=True,
        )
        canonical_by_key[name.casefold()] = name
        for alias in aliases.split("、"):
            canonical_by_key[alias.casefold()] = name

    models_with_brand = (
        VehicleModel,
        SalesSourceBrandPolicy,
        DealerVolumeBonusRule,
        BrandRegistrationFeeRule,
    )
    existing_values = set()
    for model in models_with_brand:
        existing_values.update(
            value.strip()
            for value in model.objects.values_list("brand", flat=True)
            if value and value.strip()
        )

    for value in sorted(existing_values, key=str.casefold):
        canonical = canonical_by_key.get(value.casefold())
        if not canonical:
            VehicleBrand.objects.create(
                name=value,
                display_order=900,
                active=True,
                note="由既有資料建立",
            )
            canonical_by_key[value.casefold()] = value

    unique_fields = {
        VehicleModel: ("name", "model_number", "model_year", "model_code"),
        SalesSourceBrandPolicy: ("source_id", "effective_from"),
        DealerVolumeBonusRule: ("dealer_id", "starts_on", "ends_on"),
        BrandRegistrationFeeRule: (
            "energy_type",
            "electric_registration_class",
            "min_cc",
            "max_cc",
            "effective_from",
        ),
    }
    for model in models_with_brand:
        for row in model.objects.all().iterator():
            canonical = canonical_by_key.get((row.brand or "").strip().casefold())
            if not canonical or row.brand == canonical:
                continue
            duplicate_filter = {
                field: getattr(row, field) for field in unique_fields[model]
            }
            if model.objects.filter(
                brand=canonical, **duplicate_filter
            ).exclude(pk=row.pk).exists():
                # 不自動合併具有各自商業內容的規則；保留原列供人工確認。
                continue
            model.objects.filter(pk=row.pk).update(brand=canonical)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0059_electric_registration_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="品牌名稱")),
                (
                    "aliases",
                    models.TextField(
                        blank=True,
                        help_text="可用逗號、頓號或換行分隔，例如：台鈴、台鈴 Suzuki。",
                        verbose_name="別名／原廠寫法",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="顯示順序"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="內部備註"
                    ),
                ),
            ],
            options={
                "verbose_name": "車輛品牌",
                "verbose_name_plural": "車輛品牌",
                "ordering": ["display_order", "name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_vehicle_brand_name_ci",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_and_normalize_brands, migrations.RunPython.noop),
    ]
