# Generated by Django 5.2.16 on 2026-08-15 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0061_vehicle_brand_hierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclebrand",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="車行價目表與列印文件使用；建議透明背景 PNG 或清晰橫式圖片。",
                upload_to="brands/logos/%Y/%m/",
                verbose_name="品牌 LOGO",
            ),
        ),
        migrations.CreateModel(
            name="DealerPriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("period_month", models.DateField(verbose_name="價目表月份")),
                (
                    "revision",
                    models.PositiveSmallIntegerField(default=1, verbose_name="修訂版"),
                ),
                ("title", models.CharField(max_length=160, verbose_name="價目表標題")),
                ("effective_from", models.DateField(verbose_name="生效日期")),
                (
                    "header_note",
                    models.CharField(
                        blank=True,
                        default="不含牌險，依監理單據另收",
                        max_length=250,
                        verbose_name="頁首提醒",
                    ),
                ),
                ("footer_note", models.TextField(blank=True, verbose_name="頁尾說明")),
                (
                    "installment_periods",
                    models.JSONField(
                        default=list,
                        help_text="依序保存價目表要顯示的期數。",
                        verbose_name="顯示分期期數",
                    ),
                ),
                (
                    "logo_override",
                    models.ImageField(
                        blank=True,
                        help_text="留空即使用品牌主檔 LOGO。",
                        upload_to="dealer_price_lists/logos/%Y/%m/",
                        verbose_name="本期 LOGO",
                    ),
                ),
                (
                    "brand_name_snapshot",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="品牌名稱快照"
                    ),
                ),
                (
                    "published_logo",
                    models.ImageField(
                        blank=True,
                        upload_to="dealer_price_lists/published/%Y/%m/",
                        verbose_name="發布 LOGO 快照",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已發布"),
                            ("archived", "已封存"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="發布時間"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealer_price_lists",
                        to="sales.vehiclebrand",
                        verbose_name="品牌",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dealer_price_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立人員",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_dealer_price_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發布人員",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行價目表",
                "verbose_name_plural": "車行價目表",
                "ordering": [
                    "-period_month",
                    "brand__display_order",
                    "brand__name",
                    "-revision",
                ],
            },
        ),
        migrations.CreateModel(
            name="DealerPriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="列印顯示")),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("domestic", "一般車款"),
                            ("imported", "進口車"),
                            ("other", "其他"),
                        ],
                        default="domestic",
                        max_length=20,
                        verbose_name="表格區段",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="顯示順序"
                    ),
                ),
                (
                    "model_label",
                    models.CharField(max_length=160, verbose_name="機種顯示名稱"),
                ),
                (
                    "year_label",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="年份顯示"
                    ),
                ),
                (
                    "colors_label",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="車色顯示"
                    ),
                ),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="建議售價",
                    ),
                ),
                (
                    "cash_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="現金優惠折抵",
                    ),
                ),
                (
                    "cash_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="現金價",
                    ),
                ),
                (
                    "installments",
                    models.JSONField(blank=True, default=dict, verbose_name="分期內容"),
                ),
                (
                    "customer_gift",
                    models.TextField(blank=True, verbose_name="顧客贈品"),
                ),
                (
                    "channel_label",
                    models.CharField(blank=True, max_length=80, verbose_name="通路"),
                ),
                ("note", models.TextField(blank=True, verbose_name="列印備註")),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.dealerpricelist",
                        verbose_name="價目表",
                    ),
                ),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealer_price_list_items",
                        to="sales.vehiclemodel",
                        verbose_name="車型",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行價目表車型",
                "verbose_name_plural": "車行價目表車型",
                "ordering": ["section", "display_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="dealerpricelist",
            index=models.Index(
                fields=["brand", "period_month", "status"],
                name="dealer_price_list_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="dealerpricelist",
            constraint=models.UniqueConstraint(
                fields=("brand", "period_month", "revision"),
                name="unique_dealer_price_list_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="dealerpricelistitem",
            constraint=models.UniqueConstraint(
                fields=("price_list", "vehicle_model"),
                name="unique_dealer_price_list_vehicle",
            ),
        ),
    ]
