# Generated by Django 5.2.16 on 2026-08-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0062_monthly_dealer_price_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclebrand",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="品牌識別與列印文件使用；建議透明背景 PNG 或清晰橫式圖片。",
                upload_to="brands/logos/%Y/%m/",
                verbose_name="品牌 LOGO",
            ),
        ),
        migrations.DeleteModel(
            name="DealerPriceListItem",
        ),
        migrations.DeleteModel(
            name="DealerPriceList",
        ),
    ]
