# Generated by Django 5.2.16 on 2026-08-18 03:09

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0063_remove_dealer_price_lists"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleFactoryModelCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("code", models.CharField(max_length=120, verbose_name="原廠型號")),
                (
                    "normalized_code",
                    models.CharField(
                        editable=False, max_length=160, verbose_name="標準化原廠型號"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
            ],
            options={
                "verbose_name": "原廠型號",
                "verbose_name_plural": "原廠型號",
                "ordering": ["family", "code", "id"],
            },
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="factory_model_codes",
            field=models.ManyToManyField(
                blank=True,
                related_name="versions",
                to="sales.vehiclefactorymodelcode",
                verbose_name="適用原廠型號",
            ),
        ),
        migrations.CreateModel(
            name="VehicleModelFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="品牌")),
                ("name", models.CharField(max_length=120, verbose_name="機種")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
            ],
            options={
                "verbose_name": "機種主檔",
                "verbose_name_plural": "機種主檔",
                "ordering": ["brand", "name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("brand"),
                        django.db.models.functions.text.Lower("name"),
                        name="unique_vehicle_model_family_ci",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="vehiclefactorymodelcode",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factory_model_codes",
                to="sales.vehiclemodelfamily",
                verbose_name="機種",
            ),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="family",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="sales.vehiclemodelfamily",
                verbose_name="所屬機種",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiclefactorymodelcode",
            constraint=models.UniqueConstraint(
                fields=("family", "normalized_code"),
                name="unique_factory_model_code_in_family",
            ),
        ),
    ]
