# Generated by Django 5.2.16 on 2026-08-18 11:52

import django.core.validators
from django.db import migrations, models


def classify_existing_disbursement_rules(apps, schema_editor):
    option_model = apps.get_model("sales", "InstallmentPlanOption")
    option_model.objects.filter(expected_disbursement_rate__isnull=True).update(
        expected_disbursement_method="manual"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0066_vehicle_price_registration_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="installmentplanoption",
            name="expected_disbursement_fixed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="固定預估撥款金額",
            ),
        ),
        migrations.AddField(
            model_name="installmentplanoption",
            name="expected_disbursement_method",
            field=models.CharField(
                choices=[
                    ("rate", "按比例試算"),
                    ("fixed", "固定金額"),
                    ("manual", "本單另填"),
                ],
                default="rate",
                help_text="按比例以車款售價試算；固定金額直接帶入；特殊案件可選本單另填。",
                max_length=20,
                verbose_name="預估撥款方式",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="expected_amount_overridden",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="預計金額已人工調整"
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="expected_amount_override_reason",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="預計金額調整原因"
            ),
        ),
        migrations.RunPython(
            classify_existing_disbursement_rules,
            migrations.RunPython.noop,
        ),
    ]
