# Generated by Django 5.2.17 on 2026-08-20 07:00

from django.db import migrations, models


def split_legacy_fixed_rules(apps, schema_editor):
    Rule = apps.get_model("sales", "BrandRegistrationFeeRule")
    Rule.objects.filter(calculation_type="fixed", energy_type="electric").update(
        calculation_type="fixed_components"
    )
    Rule.objects.filter(calculation_type="fixed").update(
        calculation_type="fixed_bundle"
    )


def restore_legacy_fixed_rules(apps, schema_editor):
    Rule = apps.get_model("sales", "BrandRegistrationFeeRule")
    Rule.objects.filter(
        calculation_type__in=("fixed_bundle", "fixed_components")
    ).update(calculation_type="fixed")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0072_vehiclebrand_logo_crop"),
    ]

    operations = [
        migrations.RunPython(
            split_legacy_fixed_rules,
            restore_legacy_fixed_rules,
        ),
        migrations.AlterField(
            model_name="brandregistrationfeerule",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("formula", "公式計算"),
                    ("fixed_bundle", "固定整包金額"),
                    ("fixed_components", "固定分項金額"),
                    ("manual", "人工輸入"),
                ],
                max_length=20,
                verbose_name="計算方式",
            ),
        ),
    ]
