# Generated by Django 5.2.17 on 2026-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0074_canonicalize_gsx250f_model_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandregistrationfeerule",
            name="energy_type",
            field=models.CharField(
                choices=[
                    ("gas", "油車"),
                    ("electric", "電動車"),
                    ("light_electric", "輕型電動車"),
                    ("micro_electric", "微型電動二輪車"),
                ],
                default="gas",
                max_length=20,
                verbose_name="能源別",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="displacement_cc",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="油車領牌試算使用；電動車、輕型電動車與微型電動二輪車可留空。",
                null=True,
                verbose_name="排氣量（c.c.）",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="electric_registration_class",
            field=models.CharField(
                blank=True,
                choices=[("light", "輕型電動機車"), ("heavy", "重型電動機車")],
                help_text="電動車使用；輕型電動車會自動套用輕型級別，不會由馬達功率推算。",
                max_length=20,
                verbose_name="電動車領牌級別",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="energy_type",
            field=models.CharField(
                choices=[
                    ("gas", "油車"),
                    ("electric", "電動車"),
                    ("light_electric", "輕型電動車"),
                    ("micro_electric", "微型電動二輪車"),
                ],
                max_length=20,
                verbose_name="動力類型",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="horsepower_hp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="電動車、輕型電動車或微型電動二輪車選填；不會由 kW 自動換算。",
                max_digits=8,
                null=True,
                verbose_name="馬力（HP）",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="motor_power_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="電動車、輕型電動車或微型電動二輪車選填；不會自動換算馬力。",
                max_digits=8,
                null=True,
                verbose_name="馬達功率（kW）",
            ),
        ),
    ]
