# Generated by Django 5.2.17 on 2026-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0075_alter_brandregistrationfeerule_energy_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="vehicle_price_adjustment_reason",
            field=models.TextField(
                blank=True,
                help_text="成交車價與售價版本不同時，記錄本次人工調整原因。",
                verbose_name="車價調整原因",
            ),
        ),
    ]
