# Generated by Django 5.2.17 on 2026-08-22 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0076_salesorder_vehicle_price_adjustment_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAppearancePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("professional", "專業藍綠"),
                            ("deep-blue", "沉穩深藍"),
                            ("graphite-gold", "石墨灰金"),
                            ("bright-indigo", "明亮靛藍"),
                            ("high-contrast", "高對比"),
                        ],
                        default="professional",
                        max_length=30,
                        verbose_name="介面主題",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用者外觀偏好",
                "verbose_name_plural": "使用者外觀偏好",
            },
        ),
    ]
