# Generated by Django 5.2.17 on 2026-08-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0080_alter_vehiclemodel_model_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userappearancepreference",
            name="theme",
            field=models.CharField(
                choices=[
                    ("professional", "專業藍綠"),
                    ("night-blue", "夜間深藍"),
                    ("system", "跟隨裝置"),
                    ("deep-blue", "沉穩深藍"),
                    ("graphite-gold", "石墨灰金"),
                    ("bright-indigo", "明亮靛藍"),
                    ("high-contrast", "高對比"),
                ],
                default="professional",
                max_length=30,
                verbose_name="介面主題",
            ),
        ),
    ]
