# Generated by Django 5.2.17 on 2026-08-25 04:50

import django.db.models.deletion
from django.db import migrations, models


def populate_location_labels(apps, schema_editor):
    VehicleInventoryHistory = apps.get_model("sales", "VehicleInventoryHistory")

    def label_for(store):
        if store is None:
            return "本店"
        if (store.code or "").casefold() == "hq" or store.name in {"本店", "總店"}:
            return "本店"
        return store.name

    for history in VehicleInventoryHistory.objects.select_related(
        "location_store_snapshot", "from_location", "to_location"
    ).iterator():
        history.location_label_snapshot = label_for(history.location_store_snapshot)
        history.from_location_label = (
            label_for(history.from_location) if history.from_location_id else ""
        )
        history.to_location_label = (
            label_for(history.to_location) if history.to_location_id else ""
        )
        history.save(
            update_fields=[
                "location_label_snapshot",
                "from_location_label",
                "to_location_label",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0081_add_dark_and_system_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinventory",
            name="current_dealer",
            field=models.ForeignKey(
                blank=True,
                help_text="未選擇代表車輛位於本店；調往合作車行時才需選擇車行名稱。",
                limit_choices_to={"source_type": "dealer"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="located_vehicles",
                to="sales.salessource",
                verbose_name="實際位置／合作車行",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventoryhistory",
            name="from_location_label",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="調出實際位置"
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventoryhistory",
            name="location_label_snapshot",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="當下實際位置"
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventoryhistory",
            name="to_location_label",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="調入實際位置"
            ),
        ),
        migrations.RunPython(populate_location_labels, migrations.RunPython.noop),
    ]
