# Generated by Django 5.2.17 on 2026-08-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0082_inventory_actual_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinventory",
            name="current_dealer",
            field=models.ForeignKey(
                blank=True,
                help_text="未選擇代表車輛位於本店；放在車行時請選擇車行名稱。",
                limit_choices_to={"source_type": "dealer"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="located_vehicles",
                to="sales.salessource",
                verbose_name="實際位置",
            ),
        ),
    ]
