# Generated by Django 5.2.17 on 2026-08-26 04:44

from django.db import migrations, models


LEGACY_LINE_GROUP_MARKER = "已加入 LINE 群組"


def split_legacy_line_group_flag(apps, schema_editor):
    SalesSource = apps.get_model("sales", "SalesSource")
    for source in SalesSource.objects.filter(
        relationship_note__icontains=LEGACY_LINE_GROUP_MARKER
    ).iterator():
        parts = [
            part.strip()
            for part in (source.relationship_note or "").replace("，", "、").split("、")
            if part.strip()
        ]
        if LEGACY_LINE_GROUP_MARKER not in parts:
            continue
        source.has_line_group = True
        source.relationship_note = "、".join(
            part for part in parts if part != LEGACY_LINE_GROUP_MARKER
        )
        source.save(update_fields=["has_line_group", "relationship_note"])


def merge_legacy_line_group_flag(apps, schema_editor):
    SalesSource = apps.get_model("sales", "SalesSource")
    for source in SalesSource.objects.filter(has_line_group=True).iterator():
        parts = [
            part.strip()
            for part in (source.relationship_note or "").replace("，", "、").split("、")
            if part.strip()
        ]
        if LEGACY_LINE_GROUP_MARKER not in parts:
            parts.insert(0, LEGACY_LINE_GROUP_MARKER)
        source.relationship_note = "、".join(parts)
        source.save(update_fields=["relationship_note"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0085_clean_legacy_odoo_note_markers"),
    ]

    operations = [
        migrations.AddField(
            model_name="salessource",
            name="has_line_group",
            field=models.BooleanField(
                default=False,
                help_text="只記錄是否有車行 LINE 群組；不會影響價格表提供對象。",
                verbose_name="有 LINE 群組",
            ),
        ),
        migrations.AddField(
            model_name="salessource",
            name="line_group_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sym_only", "純 SYM"),
                    ("suzuki_all", "純 SUZUKI 油電"),
                    ("suzuki_electric", "純 SUZUKI 電"),
                    ("all", "都有"),
                ],
                help_text="記錄群組內涵蓋的品牌範圍，與商務合作類別分開管理。",
                max_length=30,
                verbose_name="LINE 群組特性",
            ),
        ),
        migrations.RunPython(
            split_legacy_line_group_flag,
            merge_legacy_line_group_flag,
        ),
    ]
