# Generated by Django 5.2.17 on 2026-08-26 08:44

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


COOPERATION_SCOPES = ("sym", "suzuki_gas", "suzuki_electric")


def _append_contact(base, value):
    value = (value or "").strip()
    if not value:
        return base
    parts = [part.strip() for part in (base or "").split("／") if part.strip()]
    if value not in parts:
        parts.append(value)
    return "／".join(parts)


def populate_contact_and_cooperation_profiles(apps, schema_editor):
    SalesSource = apps.get_model("sales", "SalesSource")
    BrandPolicy = apps.get_model("sales", "SalesSourceBrandPolicy")
    CooperationProfile = apps.get_model(
        "sales", "SalesSourceCooperationProfile"
    )
    today = timezone.localdate()

    for source in SalesSource.objects.all().iterator():
        updates = {}
        other_contact = source.other_contact
        if source.fax:
            other_contact = _append_contact(other_contact, f"傳真：{source.fax}")

        for line in (source.note or "").splitlines():
            if not line.startswith(("歷史聯絡資料：", "歷史其他聯絡資料")):
                continue
            identity, separator, details_text = line.partition("｜")
            if identity.startswith("歷史聯絡資料：") and not source.responsible_person:
                responsible = identity.removeprefix("歷史聯絡資料：").strip()
                if "（" in responsible:
                    responsible = responsible.split("（", 1)[0].strip()
                if responsible:
                    updates["responsible_person"] = responsible
                    source.responsible_person = responsible
            if not separator:
                continue
            for detail in details_text.split("／"):
                detail = detail.strip()
                if not detail:
                    continue
                label, detail_separator, value = detail.partition("：")
                value = value.strip() if detail_separator else detail
                if label == "電話" and value and not source.phone:
                    updates["phone"] = value
                    source.phone = value
                elif label == "電話二" and value and not source.phone_secondary:
                    updates["phone_secondary"] = value
                    source.phone_secondary = value
                elif label == "手機" and value and not source.mobile:
                    updates["mobile"] = value
                    source.mobile = value
                else:
                    other_contact = _append_contact(other_contact, detail)
        if other_contact != source.other_contact:
            updates["other_contact"] = other_contact
        if updates:
            SalesSource.objects.filter(pk=source.pk).update(**updates)

        if source.source_type != "dealer":
            continue
        for scope in COOPERATION_SCOPES:
            current = (
                BrandPolicy.objects.filter(
                    source_id=source.pk,
                    cooperation_scope=scope,
                    effective_from__lte=today,
                )
                .filter(Q(effective_to__isnull=True) | Q(effective_to__gte=today))
                .order_by("-effective_from", "-pk")
                .first()
            )
            cooperates = bool(current and current.cooperates)
            CooperationProfile.objects.get_or_create(
                source_id=source.pk,
                cooperation_scope=scope,
                defaults={
                    "cooperates": cooperates,
                    "relationship_type": "general",
                    "vehicle_capacity": source.vehicle_capacity if cooperates else None,
                    "note": "",
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0087_consolidate_sales_source_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="salessource",
            name="mobile",
            field=models.CharField(blank=True, max_length=50, verbose_name="手機"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="other_contact",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="其他聯絡方式"
            ),
        ),
        migrations.AddField(
            model_name="salessource",
            name="phone_secondary",
            field=models.CharField(blank=True, max_length=50, verbose_name="電話二"),
        ),
        migrations.AddField(
            model_name="salessource",
            name="responsible_person",
            field=models.CharField(blank=True, max_length=80, verbose_name="負責人"),
        ),
        migrations.AlterField(
            model_name="salessource",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="電話一"),
        ),
        migrations.CreateModel(
            name="SalesSourceCooperationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "cooperation_scope",
                    models.CharField(
                        choices=[
                            ("sym", "三陽 SYM"),
                            ("suzuki_gas", "台鈴油車"),
                            ("suzuki_electric", "台鈴電車"),
                        ],
                        max_length=30,
                        verbose_name="合作類別",
                    ),
                ),
                (
                    "cooperates",
                    models.BooleanField(
                        default=False, verbose_name="提供價格表／有合作"
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("general", "一般"),
                            ("exclusive", "專銷"),
                            ("shareholder", "股東"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="關係類型",
                    ),
                ),
                (
                    "vehicle_capacity",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="可停放數量"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="合作備註")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooperation_profiles",
                        to="sales.salessource",
                        verbose_name="合作車行",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行合作資料",
                "verbose_name_plural": "車行合作資料",
                "ordering": ["source", "cooperation_scope"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "cooperation_scope"),
                        name="unique_source_cooperation_profile",
                    )
                ],
            },
        ),
        migrations.RunPython(
            populate_contact_and_cooperation_profiles,
            migrations.RunPython.noop,
        ),
    ]
