# Generated by Django 5.2.17 on 2026-08-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0093_remove_settlement_cost_county"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderoperationsprofile",
            name="incentive_installment_rate_rule",
        ),
        migrations.RemoveField(
            model_name="orderoperationsprofile",
            name="incentive_installment_periods",
        ),
        migrations.RemoveField(
            model_name="orderoperationsprofile",
            name="incentive_installment_rate",
        ),
        migrations.DeleteModel(
            name="VehicleIncentiveInstallmentRate",
        ),
    ]
