# Generated by Django 5.2.17 on 2026-08-29 04:04

from django.db import migrations, models


def migrate_shared_capacities(apps, schema_editor):
    SalesSource = apps.get_model("sales", "SalesSource")
    CooperationProfile = apps.get_model(
        "sales", "SalesSourceCooperationProfile"
    )
    for source in SalesSource.objects.all().iterator():
        profiles = {
            profile.cooperation_scope: profile
            for profile in CooperationProfile.objects.filter(source_id=source.pk)
        }
        sym_profile = profiles.get("sym")
        suzuki_profiles = [
            profiles.get("suzuki_gas"),
            profiles.get("suzuki_electric"),
        ]
        sym_capacity = sym_profile.vehicle_capacity if sym_profile else None
        suzuki_values = [
            profile.vehicle_capacity
            for profile in suzuki_profiles
            if profile and profile.vehicle_capacity is not None
        ]
        suzuki_capacity = max(suzuki_values) if suzuki_values else None

        # 早期資料只有一個總容量欄位。只有合作範圍單一時才可安全判斷歸屬；
        # 同時合作三陽與台鈴時不猜測，優先保留各合作設定內既有的容量。
        legacy_capacity = source.vehicle_capacity
        sym_cooperates = bool(sym_profile and sym_profile.cooperates)
        suzuki_cooperates = any(
            profile and profile.cooperates for profile in suzuki_profiles
        )
        if legacy_capacity is not None:
            if sym_capacity is None and sym_cooperates and not suzuki_cooperates:
                sym_capacity = legacy_capacity
            if suzuki_capacity is None and suzuki_cooperates and not sym_cooperates:
                suzuki_capacity = legacy_capacity

        source.sym_vehicle_capacity = sym_capacity
        source.suzuki_vehicle_capacity = suzuki_capacity
        source.save(
            update_fields=["sym_vehicle_capacity", "suzuki_vehicle_capacity"]
        )


def restore_profile_capacities(apps, schema_editor):
    SalesSource = apps.get_model("sales", "SalesSource")
    CooperationProfile = apps.get_model(
        "sales", "SalesSourceCooperationProfile"
    )
    for source in SalesSource.objects.all().iterator():
        capacities = [
            value
            for value in (
                source.sym_vehicle_capacity,
                source.suzuki_vehicle_capacity,
            )
            if value is not None
        ]
        source.vehicle_capacity = max(capacities) if capacities else None
        source.save(update_fields=["vehicle_capacity"])
        CooperationProfile.objects.filter(
            source_id=source.pk, cooperation_scope="sym"
        ).update(vehicle_capacity=source.sym_vehicle_capacity)
        CooperationProfile.objects.filter(
            source_id=source.pk,
            cooperation_scope__in=("suzuki_gas", "suzuki_electric"),
        ).update(vehicle_capacity=source.suzuki_vehicle_capacity)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0098_salessource_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="salessource",
            name="suzuki_vehicle_capacity",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="台鈴油電共用排車容量"
            ),
        ),
        migrations.AddField(
            model_name="salessource",
            name="sym_vehicle_capacity",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="三陽排車容量"
            ),
        ),
        migrations.RunPython(
            migrate_shared_capacities,
            restore_profile_capacities,
        ),
        migrations.RemoveField(
            model_name="salessourcecooperationprofile",
            name="vehicle_capacity",
        ),
        migrations.RemoveField(
            model_name="salessource",
            name="vehicle_capacity",
        ),
    ]
