# Generated by Django 5.2.17 on 2026-08-31 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0102_convert_employee_purchase_platforms_to_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSourcePlatformContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "contact_person",
                    models.CharField(max_length=250, verbose_name="聯絡人"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=100, verbose_name="電話"),
                ),
                (
                    "extension",
                    models.CharField(blank=True, max_length=50, verbose_name="分機"),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=100, verbose_name="手機"),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=500, verbose_name="信箱"),
                ),
                ("note", models.TextField(blank=True, verbose_name="補充資料")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="顯示順序"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_contacts",
                        to="sales.salessource",
                        verbose_name="網路平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "網路平台聯絡窗口",
                "verbose_name_plural": "網路平台聯絡窗口",
                "ordering": ["source", "display_order", "id"],
            },
        ),
    ]
