# Generated by Django 5.2.17 on 2026-08-31 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0104_import_network_platform_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="salessource",
            name="staff_commission",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="每筆歸屬此銷售人員的基礎傭金；供後續人員傭金結算引用。",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="傭金",
            ),
        ),
        migrations.AddField(
            model_name="salessource",
            name="staff_stores",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="本店人員可同時隸屬永湛與馭盛。",
                verbose_name="所在店",
            ),
        ),
    ]
