# Generated by Django 5.2.17 on 2026-09-01 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0106_assign_network_platform_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceListDistributionMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="固定儲存該月 1 日。",
                        unique=True,
                        verbose_name="分發月份",
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="建立方式"
                    ),
                ),
            ],
            options={
                "verbose_name": "每月價格表分發清單",
                "verbose_name_plural": "每月價格表分發清單",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="PriceListDistributionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "dealer_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="車行代碼快照"
                    ),
                ),
                (
                    "dealer_name",
                    models.CharField(max_length=120, verbose_name="車行名稱快照"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="縣市快照"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="行政區快照"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="地址快照"
                    ),
                ),
                (
                    "requires_sym",
                    models.BooleanField(default=False, verbose_name="提供三陽價格表"),
                ),
                (
                    "requires_suzuki",
                    models.BooleanField(default=False, verbose_name="提供台鈴價格表"),
                ),
                (
                    "sym_exclusive",
                    models.BooleanField(default=False, verbose_name="三陽專銷"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="已完成"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "completed_by",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="完成人員"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="當月備註")),
                (
                    "dealer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_list_distribution_items",
                        to="sales.salessource",
                        verbose_name="合作車行",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.pricelistdistributionmonth",
                        verbose_name="分發月份",
                    ),
                ),
            ],
            options={
                "verbose_name": "每月價格表分發明細",
                "verbose_name_plural": "每月價格表分發明細",
                "ordering": ["city", "district", "dealer_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["distribution", "completed", "city", "district"],
                        name="price_dist_month_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dealer__isnull", False)),
                        fields=("distribution", "dealer"),
                        name="unique_price_list_month_dealer",
                    )
                ],
            },
        ),
    ]
