# Generated by Django 5.2.17 on 2026-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0107_pricelistdistributionmonth_pricelistdistributionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelistdistributionitem",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="聯絡電話快照"
            ),
        ),
    ]
