# Generated by Django 5.2.17 on 2026-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0108_add_price_distribution_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userappearancepreference",
            name="mobile_quick_links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="依顯示順序保存每個帳號選用的手機快捷功能代碼。",
                verbose_name="手機快速前往",
            ),
        ),
    ]
