# Generated by Django 5.2.17 on 2026-09-02 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0109_user_mobile_quick_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelistdistributionitem",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_price_list_distribution_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="當月負責人",
            ),
        ),
        migrations.AddField(
            model_name="pricelistdistributionitem",
            name="assigned_to_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="負責人名稱快照"
            ),
        ),
        migrations.AddField(
            model_name="pricelistdistributionitem",
            name="visit_order",
            field=models.PositiveIntegerField(default=0, verbose_name="拜訪順序"),
        ),
        migrations.AddField(
            model_name="pricelistdistributionmonth",
            name="assignment_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="分工確認時間"
            ),
        ),
        migrations.AddField(
            model_name="pricelistdistributionmonth",
            name="assignment_confirmed_by",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="分工確認人員"
            ),
        ),
        migrations.AddIndex(
            model_name="pricelistdistributionitem",
            index=models.Index(
                fields=["distribution", "assigned_to", "visit_order"],
                name="price_dist_owner_order_idx",
            ),
        ),
    ]
