# Generated by Django 5.2.17 on 2026-09-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0110_price_distribution_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealervolumebonusallocation",
            name="original_commission_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="原傭金快照（含車行加減額）",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="commission_recipient",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"source_type": "dealer"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credited_orders",
                to="sales.salessource",
                verbose_name="台數與傭金歸屬車行",
            ),
        ),
    ]
