# Generated by Django 5.2.17 on 2026-09-03 11:10

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_brands(apps, schema_editor):
    Rule = apps.get_model('sales', 'DealerVolumeBonusRule')
    Brand = apps.get_model('sales', 'DealerVolumeBonusBrand')
    alias = schema_editor.connection.alias
    for rule in Rule.objects.using(alias).exclude(brand='').iterator():
        Brand.objects.using(alias).get_or_create(rule_id=rule.pk, brand=rule.brand)


def verify_reverse_is_safe(apps, schema_editor):
    Rule = apps.get_model('sales', 'DealerVolumeBonusRule')
    alias = schema_editor.connection.alias
    for rule in Rule.objects.using(alias).prefetch_related('brands').iterator(chunk_size=200):
        names = [item.brand for item in rule.brands.all()]
        if names and names != [rule.brand]:
            raise RuntimeError('此資料庫已有新版品牌集合，不能直接降版；請保留新資料並依備份還原流程處理。')


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0114_volume_bonus_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealervolumebonusrule",
            name="period_type",
            field=models.CharField(
                choices=[("month", "按月"), ("quarter", "按季"), ("custom", "自訂")],
                default="custom",
                max_length=10,
                verbose_name="統計方式",
            ),
        ),
        migrations.CreateModel(
            name="DealerVolumeBonusBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="品牌名稱快照")),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="sales.dealervolumebonusrule",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "brand"), name="unique_bonus_rule_brand"
                    )
                ],
            },
        ),
        migrations.RunPython(copy_legacy_brands, verify_reverse_is_safe),
    ]
