# Generated by Django 5.2.17 on 2026-09-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def prevent_audit_loss_on_reverse(apps, schema_editor):
    Audit = apps.get_model("sales", "DealerVolumeBonusDeletion")
    if Audit.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("已有規則刪除紀錄，不能逆向刪除稽核表；請保留紀錄再評估回復。")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0116_bonus_multiple_periods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerVolumeBonusDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_rule_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="原規則編號"
                    ),
                ),
                ("rule_name", models.TextField(verbose_name="刪除時名稱")),
                (
                    "actor_name",
                    models.CharField(max_length=150, verbose_name="操作人員快照"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="刪除時間"),
                ),
                ("snapshot", models.JSONField(verbose_name="原規則完整設定")),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bonus_rule_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "台數獎金規則刪除紀錄",
                "verbose_name_plural": "台數獎金規則刪除紀錄",
                "ordering": ["-deleted_at", "-pk"],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, prevent_audit_loss_on_reverse),
    ]
