# Generated by Django 5.2.17 on 2026-09-04 03:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0117_bonus_rule_deletion_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerVehicleRewardPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="生效日期"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealer_reward_plans",
                        to="sales.vehiclemodel",
                        verbose_name="車型",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行附加獎勵方案",
                "verbose_name_plural": "車行附加獎勵方案",
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DealerVehicleRewardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("physical", "實物"),
                            ("cash_gift", "紅包／現金"),
                            ("voucher", "禮券／兌換券"),
                            ("travel_points", "旅遊點數"),
                        ],
                        max_length=24,
                        verbose_name="類型",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="獎勵名稱")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="數量／金額／點數",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="單位"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="說明"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.dealervehiclerewardplan",
                        verbose_name="獎勵方案",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行附加獎勵項目",
                "verbose_name_plural": "車行附加獎勵項目",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dealervehiclerewardplan",
            constraint=models.UniqueConstraint(
                fields=("vehicle_model", "effective_from"),
                name="unique_dealer_reward_plan_start",
            ),
        ),
    ]
