# Generated by Django 5.2.17 on 2026-09-04 07:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def create_catalog_items_for_existing_rewards(apps, schema_editor):
    reward_model = apps.get_model("sales", "DealerVehicleRewardItem")
    catalog_model = apps.get_model("sales", "DealerRewardCatalogItem")
    default_units = {
        "physical": "件",
        "cash_gift": "元",
        "voucher": "元",
        "travel_points": "點",
    }
    for reward in reward_model.objects.all().iterator():
        unit = (reward.unit or "").strip() or default_units.get(reward.reward_type, "件")
        catalog_item, _ = catalog_model.objects.get_or_create(
            reward_type=reward.reward_type,
            name=(reward.name or "").strip(),
            unit=unit,
        )
        reward_model.objects.filter(pk=reward.pk).update(
            catalog_item_id=catalog_item.pk,
            unit=unit,
        )


def remove_generated_catalog_items(apps, schema_editor):
    reward_model = apps.get_model("sales", "DealerVehicleRewardItem")
    catalog_model = apps.get_model("sales", "DealerRewardCatalogItem")
    reward_model.objects.update(catalog_item_id=None)
    catalog_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0118_dealer_vehicle_reward_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealervehiclerewarditem",
            name="cost_effective_on_snapshot",
            field=models.DateField(
                blank=True, null=True, verbose_name="成本快照基準日"
            ),
        ),
        migrations.AddField(
            model_name="dealervehiclerewarditem",
            name="unit_cost_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="單位成本快照",
            ),
        ),
        migrations.CreateModel(
            name="DealerRewardCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("physical", "實物"),
                            ("cash_gift", "紅包／現金"),
                            ("voucher", "禮券／兌換券"),
                            ("travel_points", "旅遊點數"),
                        ],
                        max_length=24,
                        verbose_name="類型",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="品項名稱")),
                ("unit", models.CharField(max_length=20, verbose_name="預設單位")),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="內部備註"
                    ),
                ),
            ],
            options={
                "verbose_name": "車行獎勵品項",
                "verbose_name_plural": "車行獎勵品項",
                "ordering": ["reward_type", "name", "unit"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reward_type", "name", "unit"),
                        name="unique_dealer_reward_catalog_item",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="dealervehiclerewarditem",
            name="catalog_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_items",
                to="sales.dealerrewardcatalogitem",
                verbose_name="獎勵品項",
            ),
        ),
        migrations.CreateModel(
            name="DealerRewardCostVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="單位成本",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="生效日期"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="結束日期"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="成本備註"
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_versions",
                        to="sales.dealerrewardcatalogitem",
                        verbose_name="獎勵品項",
                    ),
                ),
            ],
            options={
                "verbose_name": "車行獎勵成本版本",
                "verbose_name_plural": "車行獎勵成本版本",
                "ordering": ["-effective_from", "-id"],
                "indexes": [
                    models.Index(
                        fields=["catalog_item", "effective_from"],
                        name="dealer_reward_cost_lookup",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog_item", "effective_from"),
                        name="unique_dealer_reward_cost_start",
                    )
                ],
            },
        ),
        migrations.RunPython(
            create_catalog_items_for_existing_rewards,
            remove_generated_catalog_items,
        ),
    ]
