# Generated by Django 5.2.17 on 2026-09-11 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0123_remaining_report_readers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("published_version", models.PositiveIntegerField(default=1)),
                ("draft", models.JSONField(default=dict)),
                ("published", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "報表分類設定",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)),
                        name="report_classification_singleton",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportClassificationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("action", models.CharField(max_length=30)),
                ("snapshot", models.JSONField()),
                ("actor_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="sales.reportclassification",
                    ),
                ),
            ],
            options={
                "verbose_name": "報表分類版本",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("classification", "version"),
                        name="unique_classification_revision",
                    )
                ],
            },
        ),
    ]
