# Generated by Django 5.2.17 on 2026-09-11 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0125_seed_report_classification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccessState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configured", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_access_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "人員畫面權限狀態",
            },
        ),
        migrations.CreateModel(
            name="ReportAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view", models.BooleanField(default=False)),
                ("export", models.BooleanField(default=False)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.reportdefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "report"), name="unique_user_report_access"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("view", True), ("export", False), _connector="OR"
                        ),
                        name="report_export_requires_view",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScreenAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_key", models.CharField(max_length=40)),
                ("view", models.BooleanField(default=False)),
                ("operate", models.BooleanField(default=False)),
                ("export", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "screen_key"), name="unique_user_screen_access"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("view", True),
                            models.Q(("export", False), ("operate", False)),
                            _connector="OR",
                        ),
                        name="screen_actions_require_view",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAccessRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("before", models.JSONField()),
                ("after", models.JSONField()),
                ("actor_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "人員畫面權限歷程",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "version"), name="unique_user_access_revision"
                    )
                ],
            },
        ),
    ]
