# Generated by Django 5.2.17 on 2026-09-11 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0126_user_screen_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reportaccessgrant",
            name="report_export_requires_view",
        ),
        migrations.AddField(
            model_name="reportaccessgrant",
            name="operate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="reportaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("view", True),
                    models.Q(("export", False), ("operate", False)),
                    _connector="OR",
                ),
                name="report_actions_require_view",
            ),
        ),
    ]
