# Generated by Django 5.2.17 on 2026-09-12 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0128_production_report_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="card_installment_fee_income",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="刷卡、分期手續費合併收入",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="first_sale_bonus_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="首賣獎金支出"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="friendly_dealer_bonus_expense",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="友善車行獎金支出",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="friendly_dealer_bonus_income",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="友善車行獎金收入",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="gift_shipping_expense",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="贈品、運費合併支出",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="installment_fee_expense",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="分期手續費支出",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="legacy_finance_reconciliation",
            field=models.JSONField(
                blank=True, default=dict, editable=False, verbose_name="匯入財務核對"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="used_vehicle_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="中古車支出"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="used_vehicle_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="中古車收入"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="volume_bonus_expense",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="歷史台數獎金支出",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="yamaha_bonus_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="山葉獎金收入"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="established_on",
            field=models.DateField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.localdate,
                editable=False,
                null=True,
                verbose_name="訂單成立日期",
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="actual_disbursement",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="實際撥款"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="agency_fee_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="代辦費收入"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="card_fee_expense",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="銀行刷卡手續費支出",
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="card_fee_income",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="刷卡手續費收入",
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="compulsory_insurance_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="強制險支出"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="compulsory_insurance_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="強制險收入"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="credit_card_commission",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="信用卡傭金"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="dealer_commission_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="車行傭金支出"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="gift_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="贈品支出"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="installment_fee_income",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="分期手續費收入",
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="installment_interest_subsidy",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="分期補貼息"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="insurance_commission",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="強制險傭金"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="other_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="其他收入"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="plate_selection_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="選號支出"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="plate_selection_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="選號收入"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="promotion_subsidy",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="促銷補助金"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="registration_tax_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="領牌稅金支出"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="registration_tax_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="領牌稅金收入"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="sales_bonus",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="實銷獎勵金"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="scrap_agency_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="報廢代辦收入"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="scrap_vehicle_income",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="報廢車收入"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="shipping_expense",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="運費支出"
            ),
        ),
        migrations.AlterField(
            model_name="orderoperationsprofile",
            name="vehicle_cost",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=16, verbose_name="車輛成本"
            ),
        ),
    ]
