# Generated by Django 5.2.17 on 2026-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0129_imported_finance_and_established_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="legacy_card_fee_expense",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                max_digits=16,
                verbose_name="匯入信用卡手續費支出",
            ),
        ),
    ]
