# Generated by Django 5.2.17 on 2026-09-14 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0131_backfill_established_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("title", models.CharField(max_length=160, verbose_name="標題")),
                ("body", models.TextField(max_length=10000, verbose_name="內容")),
                ("published", models.BooleanField(default=False, verbose_name="發布")),
                ("pinned", models.BooleanField(default=False, verbose_name="置頂")),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="開始顯示時間"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="結束顯示時間"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "updated_by",
                    models.CharField(blank=True, max_length=150, verbose_name="修改人"),
                ),
            ],
            options={
                "ordering": ("-pinned", "-starts_at", "-pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="announcement_valid_window",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAnnouncementRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("content", models.JSONField()),
                ("actor_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="sales.systemannouncement",
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("announcement", "version"),
                        name="announcement_unique_revision",
                    )
                ],
            },
        ),
    ]
