# Generated by Django 5.2.17 on 2026-09-14 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0133_home_favorites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdraft",
            name="owner_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_drafts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="下單帳號",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="接單時間"),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accepted_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接單人",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="accepted_name",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="接單人名稱快照"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="下單帳號",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="trade_in_intent",
            field=models.CharField(
                choices=[("unknown", "待確認"), ("yes", "是"), ("no", "否")],
                default="unknown",
                max_length=12,
                verbose_name="是否有汰舊",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("intake_pending", "待接單"),
                    ("allocation_pending", "待配車"),
                    ("allocated", "已配車"),
                    ("transfer_pending", "待調車"),
                    ("in_transfer", "調車中"),
                    ("delivery_pending", "待交車"),
                    ("delivered_docs_pending", "已交車／待補文件"),
                    ("completed", "已完成"),
                    ("cancel_refund_pending", "取消待退款"),
                    ("cancelled", "已取消／已退款"),
                ],
                default="draft",
                max_length=32,
                verbose_name="訂單狀態",
            ),
        ),
        migrations.CreateModel(
            name="OrderAccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("internal", "店內人員"), ("dealer", "合作車行")],
                        default="internal",
                        max_length=12,
                        verbose_name="下單身分",
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.salessource",
                        verbose_name="預設店別／所屬車行",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderIntakeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("checksum", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[("installment", "分期表"), ("supplement", "補充檔案")],
                        max_length=16,
                        verbose_name="附件類型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="orders/intake/%Y/%m/", verbose_name="附件"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="原始檔名")),
                (
                    "draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_attachments",
                        to="sales.orderdraft",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_attachments",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("draft__isnull", True), ("order__isnull", False)),
                            models.Q(("draft__isnull", False), ("order__isnull", True)),
                            _connector="OR",
                        ),
                        name="intake_attachment_one_parent",
                    )
                ],
            },
        ),
    ]
