# Generated by Django 5.2.17 on 2026-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0135_intake_account_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="submission_key",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
