# Generated by Django 5.2.17 on 2026-09-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0136_order_intake_submission_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaccountprofile",
            name="can_submit_orders",
            field=models.BooleanField(
                default=True, verbose_name="可建立訂單與使用草稿"
            ),
        ),
        migrations.CreateModel(
            name="VehicleCatalogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="catalog/%Y/%m/", verbose_name="車款主圖"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=4000, verbose_name="車款介紹"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, verbose_name="上架至公開選車入口"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="排序（小的在前）"
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "vehicle_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_entry",
                        to="sales.vehiclemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
