# Generated by Django 5.2.17 on 2026-09-17 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0142_order_deletion_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="活動名稱")),
                (
                    "scheduled_on",
                    models.DateField(blank=True, null=True, verbose_name="預計送禮日"),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="活動說明"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=150)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SiteTextOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("key", models.CharField(max_length=180, unique=True)),
                ("text", models.TextField(max_length=10000)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_by", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteTextRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=180)),
                ("before", models.TextField(blank=True)),
                ("after", models.TextField(blank=True)),
                ("actor", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_adjustment_reason",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="牌險調整原因"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="registration_manual",
            field=models.BooleanField(default=False, verbose_name="自行調整牌險明細"),
        ),
        migrations.AddField(
            model_name="systemannouncement",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="封存時間"),
        ),
        migrations.AddField(
            model_name="systemannouncement",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "所有人員"),
                    ("internal", "店內人員"),
                    ("dealer", "合作車行人員"),
                    ("selected", "指定人員"),
                ],
                default="all",
                max_length=20,
                verbose_name="顯示對象",
            ),
        ),
        migrations.AddField(
            model_name="systemannouncement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="刪除時間"),
        ),
        migrations.AddField(
            model_name="systemannouncement",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="指定人員",
            ),
        ),
        migrations.CreateModel(
            name="GiftDistributionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=1500)),
                ("actor", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="sales.giftdistribution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="GiftDistributionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "recipient",
                    models.CharField(max_length=150, verbose_name="送禮對象"),
                ),
                (
                    "gift",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="禮品內容"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="工作備註"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="已完成"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_by", models.CharField(blank=True, max_length=150)),
                ("removed", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sales.giftdistribution",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.salessource",
                    ),
                ),
            ],
            options={
                "ordering": ["completed", "recipient", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("distribution", "recipient"),
                        name="gift_unique_recipient",
                    )
                ],
            },
        ),
    ]
