# Generated by Django 5.2.17 on 2026-09-17 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0143_site_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleasePublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="正式版號"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="首次成功發布時間",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="salesorder",
            name="discount_basis_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="申請折扣時的原總價",
            ),
        ),
    ]
