# Generated by Django 5.2.17 on 2026-09-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0144_release_time_discount_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftdistribution",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="installment_custom",
            field=models.BooleanField(default=False, verbose_name="其他／自訂分期"),
        ),
        migrations.AddField(
            model_name="systemannouncement",
            name="dealers",
            field=models.ManyToManyField(
                blank=True,
                related_name="announcements",
                to="sales.salessource",
                verbose_name="指定合作車行",
            ),
        ),
        migrations.AlterField(
            model_name="systemannouncement",
            name="audience",
            field=models.CharField(
                choices=[
                    ("all", "所有人員"),
                    ("internal", "店內人員"),
                    ("dealer", "合作車行人員"),
                    ("selected", "指定人員"),
                    ("dealers", "指定合作車行"),
                ],
                default="all",
                max_length=20,
                verbose_name="顯示對象",
            ),
        ),
        migrations.CreateModel(
            name="AnnouncementImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="announcements/%Y/%m/")),
                ("removed", models.BooleanField(default=False)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="sales.systemannouncement",
                    ),
                ),
            ],
        ),
    ]
