# Generated by Django 5.2.17 on 2026-09-21 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_home(apps, schema_editor):
    # 僅搬移已使用的預設公司資料；不依現有人員所屬或來源推測舊單。
    apps.get_model("sales", "PrintCompany").objects.using(schema_editor.connection.alias).get_or_create(
        key="home", defaults={"legal_name": "馭盛國際有限公司", "tax_id": "83739807",
                              "address": "新北市汐止區康寧街470號、472號", "phone": "(02)2695-1112"})


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0147_payment_receipt_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="print_company_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="訂購單公司資料留存"
            ),
        ),
        migrations.CreateModel(
            name="PrintCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "legal_name",
                    models.CharField(max_length=60, verbose_name="公司／商號全名"),
                ),
                (
                    "tax_id",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{8}$", "統一編號須為 8 碼數字。"
                            )
                        ],
                        verbose_name="統一編號",
                    ),
                ),
                ("address", models.CharField(max_length=120, verbose_name="列印地址")),
                ("phone", models.CharField(max_length=40, verbose_name="列印電話")),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_company",
                        to="sales.salessource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="print_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sales.printcompany",
                verbose_name="開單公司",
            ),
        ),
        migrations.RunPython(seed_home, migrations.RunPython.noop),
        migrations.CreateModel(
            name="PrintCompanyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("order_number", models.CharField(blank=True, max_length=24)),
                ("reason", models.TextField()),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.printcompany",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_company_changes",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
