# Generated by Django 5.2.17 on 2026-09-22 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0149_order_scope_and_customer_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaccountprofile",
            name="identity_epoch",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="OrderCustomerAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                ("identity_epoch", models.PositiveIntegerField()),
                (
                    "can_view",
                    models.BooleanField(default=True, verbose_name="查看本筆訂單"),
                ),
                (
                    "can_print",
                    models.BooleanField(default=False, verbose_name="列印客戶簽署文件"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用授權")),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "reason",
                    models.CharField(max_length=500, verbose_name="授權／撤銷原因"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_grants",
                        to="sales.orderaccountprofile",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_access_grants",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "account"),
                        name="unique_order_customer_account",
                    )
                ],
            },
        ),
    ]
