# Generated by Django 5.2.17 on 2026-09-29 06:48

import django.db.models.deletion
from django.db import migrations, models


def mark_legacy_refunds(apps, schema_editor):
    # 只標記既有已取消訂單沿用舊退款規則；不新增或改動任何金額。
    SalesOrder = apps.get_model("sales", "SalesOrder")
    SalesOrder._base_manager.filter(status="cancelled").update(refund_settled_legacy=True)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0151_customer_access_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="adjustment_reason",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=250,
                verbose_name="沖銷／退款原因",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="entry_type",
            field=models.CharField(
                choices=[("receipt", "收款"), ("reversal", "沖銷"), ("refund", "退款")],
                default="receipt",
                editable=False,
                max_length=20,
                verbose_name="款項類型",
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reversal_entries",
                to="sales.paymentrecord",
                verbose_name="沖銷對象",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="forfeit_reason",
            field=models.CharField(
                blank=True, editable=False, max_length=250, verbose_name="沒收原因"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="forfeited_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="沒收金額",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="refund_settled_legacy",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="1.19.0 前已完成取消；退款未記入收款帳本，沿用舊規則顯示與刪除。",
                verbose_name="舊制退款",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_type", "reversal")),
                fields=("reverses",),
                name="payment_single_reversal",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("entry_type", "receipt"),
                    models.Q(
                        ("received_amount__lt", 0),
                        ("expected_amount", 0),
                        ("confirmed", True),
                    ),
                    _connector="OR",
                ),
                name="payment_adjustment_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reverses__isnull", True),
                    ("entry_type", "reversal"),
                    _connector="OR",
                ),
                name="payment_reverses_only_reversal",
            ),
        ),
        migrations.RunPython(mark_legacy_refunds, migrations.RunPython.noop),
    ]
