# Generated by Django 5.2.17 on 2026-09-29 07:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0152_payment_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryrecord",
            name="on_account_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="交車時掛帳金額",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="exception_closed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="例外結案時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="exception_closed_by",
            field=models.CharField(
                blank=True, editable=False, max_length=150, verbose_name="例外結案人員"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="exception_reason",
            field=models.CharField(
                blank=True, editable=False, max_length=250, verbose_name="例外結案原因"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="exception_vehicle",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exception_orders",
                to="sales.vehicleinventory",
                verbose_name="例外結案釋回車輛",
            ),
        ),
        migrations.AddField(
            model_name="salessource",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="車行未收清先交車的累計上限；空白表示不設上限但仍追蹤掛帳，0 表示必須收清才交車。",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="掛帳額度",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="registered_on",
            field=models.DateField(
                blank=True, editable=False, null=True, verbose_name="原領牌日期"
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="registered_plate_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="領牌後棄單釋回的車輛；不是新車，只能以領牌車交易再售。",
                max_length=20,
                verbose_name="已領牌車牌",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="resale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="領牌車再售價",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="installment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "未送件"),
                    ("submitted", "審核中"),
                    ("approved", "已核准"),
                    ("rejected", "未核准"),
                ],
                default="",
                max_length=30,
                verbose_name="分期狀態",
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("intake_pending", "待接單"),
                    ("allocation_pending", "待配車"),
                    ("allocated", "已配車"),
                    ("transfer_pending", "待調車"),
                    ("in_transfer", "調車中"),
                    ("delivery_pending", "待交車"),
                    ("delivered_docs_pending", "已交車／待補文件"),
                    ("completed", "已完成"),
                    ("cancel_refund_pending", "取消待退款"),
                    ("cancelled", "已取消／已退款"),
                    ("exception_closed", "例外結案（領牌後棄單）"),
                ],
                default="draft",
                max_length=32,
                verbose_name="訂單狀態",
            ),
        ),
    ]
