# Generated by Django 5.2.17 on 2026-09-29 07:46

from django.db import migrations, models


def remap_removed_statuses(apps, schema_editor):
    """移除未使用的調車狀態；正式站核對時沒有資料，仍保守對應以防殘留。"""
    SalesOrder = apps.get_model("sales", "SalesOrder")
    VehicleInventory = apps.get_model("sales", "VehicleInventory")
    SalesOrder._base_manager.filter(status__in=["transfer_pending", "in_transfer"]).update(status="allocated")
    removed = ["transfer_pending", "in_transfer", "delivery_pending"]
    allocated_ids = SalesOrder._base_manager.filter(allocated_vehicle__isnull=False).values_list("allocated_vehicle_id", flat=True)
    VehicleInventory._base_manager.filter(status__in=removed, pk__in=allocated_ids).update(status="reserved")
    VehicleInventory._base_manager.filter(status__in=removed).update(status="available")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0153_dealer_credit_exception_close"),
    ]

    operations = [
        migrations.RunPython(remap_removed_statuses, migrations.RunPython.noop),
        migrations.AddField(
            model_name="salesorder",
            name="allocated_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="配車時間"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="allocation_skip_reason",
            field=models.CharField(
                blank=True, editable=False, max_length=250, verbose_name="配車插隊原因"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("intake_pending", "待接單"),
                    ("allocation_pending", "待配車"),
                    ("allocated", "已配車"),
                    ("delivery_pending", "待交車"),
                    ("delivered_docs_pending", "已交車／待補文件"),
                    ("completed", "已完成"),
                    ("cancel_refund_pending", "取消待退款"),
                    ("cancelled", "已取消／已退款"),
                    ("exception_closed", "例外結案（領牌後棄單）"),
                ],
                default="draft",
                max_length=32,
                verbose_name="訂單狀態",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "可銷售"),
                    ("reserved", "已預留"),
                    ("delivered", "已交車"),
                    ("condition_issue", "車況異常（暫停配車）"),
                    ("sold", "已售出"),
                    ("inactive", "停用"),
                ],
                default="available",
                max_length=30,
                verbose_name="庫存狀態",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinventoryhistory",
            name="status_snapshot",
            field=models.CharField(
                choices=[
                    ("available", "可銷售"),
                    ("reserved", "已預留"),
                    ("delivered", "已交車"),
                    ("condition_issue", "車況異常（暫停配車）"),
                    ("sold", "已售出"),
                    ("inactive", "停用"),
                ],
                max_length=30,
                verbose_name="當下狀態",
            ),
        ),
    ]
