# Generated by Django 5.2.17 on 2026-09-29 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0154_state_cleanup_allocation_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issue", "開立"),
                            ("void", "作廢"),
                            ("allowance", "折讓"),
                        ],
                        max_length=20,
                        verbose_name="類型",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=20, verbose_name="發票號碼"),
                ),
                ("invoice_date", models.DateField(verbose_name="日期")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="金額（含稅）",
                    ),
                ),
                (
                    "buyer_tax_id",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="買受人統一編號"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=250, verbose_name="原因"),
                ),
                (
                    "created_by",
                    models.CharField(max_length=150, verbose_name="登記人員"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_records",
                        to="sales.salesorder",
                        verbose_name="訂單",
                    ),
                ),
                (
                    "related_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="sales.invoicerecord",
                        verbose_name="原發票",
                    ),
                ),
            ],
            options={
                "verbose_name": "發票紀錄",
                "verbose_name_plural": "發票紀錄",
                "ordering": ["invoice_date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "issue")),
                        fields=("invoice_number",),
                        name="invoice_unique_issue_number",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "void")),
                        fields=("related_invoice",),
                        name="invoice_single_void",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "issue"), ("related_invoice__isnull", True)
                            ),
                            models.Q(
                                models.Q(("kind", "issue"), _negated=True),
                                ("related_invoice__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="invoice_related_matches_kind",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "系統內"), ("email", "Email")],
                        default="in_app",
                        max_length=20,
                        verbose_name="通道",
                    ),
                ),
                ("event_key", models.CharField(max_length=60, verbose_name="事件")),
                (
                    "dedupe_key",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="去重代碼"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="標題")),
                ("body", models.TextField(blank=True, verbose_name="內容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待發送"),
                            ("sent", "已送達"),
                            ("failed", "發送失敗"),
                            ("skipped", "未設定通道"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="嘗試次數"
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="最後錯誤"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送達時間"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="已讀時間"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dmis_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "channel", "read_at"],
                        name="notification_inbox_idx",
                    )
                ],
            },
        ),
    ]
