# Generated by Django 5.2.17 on 2026-09-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0155_invoices_notifications"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvoiceRecord",
        ),
    ]
