# Generated by Django 5.2.17 on 2026-09-30 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0156_remove_invoice_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficialCatalogCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("sym", "SYM"), ("suzuki", "SUZUKI")],
                        max_length=12,
                        verbose_name="原廠",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "等待中"),
                            ("running", "讀取中"),
                            ("succeeded", "已完成"),
                            ("failed", "失敗"),
                        ],
                        default="queued",
                        max_length=12,
                        verbose_name="狀態",
                    ),
                ),
                ("job_id", models.CharField(blank=True, max_length=80)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("pages_total", models.PositiveIntegerField(default=0)),
                ("pages_done", models.PositiveIntegerField(default=0)),
                ("entries_found", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OfficialCatalogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("sym", "SYM"), ("suzuki", "SUZUKI")],
                        max_length=12,
                        verbose_name="原廠",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(max_length=160, verbose_name="官網識別"),
                ),
                (
                    "source_url",
                    models.URLField(max_length=500, verbose_name="官網網址"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="官網名稱")),
                ("data", models.JSONField(default=dict, verbose_name="官網內容")),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "acknowledged_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="上次確認的官網內容"
                    ),
                ),
                ("acknowledged_hash", models.CharField(blank=True, max_length=64)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ignored_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="忽略時的官網內容"
                    ),
                ),
                (
                    "missing",
                    models.BooleanField(default=False, verbose_name="官網已下架"),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_check",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.officialcatalogcheck",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_catalog_links",
                        to="sales.vehiclemodel",
                        verbose_name="對應系統車型",
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "name", "source_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "source_key"),
                        name="unique_official_catalog_source",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("vehicle_model__isnull", False)),
                        fields=("vehicle_model",),
                        name="unique_official_catalog_vehicle_model",
                    ),
                ],
            },
        ),
    ]
