# Generated by Django 5.2.17 on 2026-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0157_official_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="privacy_consent_fingerprint",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                verbose_name="個資同意書簽署時內容指紋",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="privacy_consent_method",
            field=models.CharField(
                blank=True,
                choices=[("paper", "紙本上傳"), ("electronic", "電子簽署")],
                max_length=20,
                verbose_name="個資同意書簽署方式",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="signed_contract_fingerprint",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                verbose_name="合約簽署時內容指紋",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="signed_contract_method",
            field=models.CharField(
                blank=True,
                choices=[("paper", "紙本上傳"), ("electronic", "電子簽署")],
                max_length=20,
                verbose_name="合約簽署方式",
            ),
        ),
    ]
