# Generated by Django 5.2.17 on 2026-10-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0159_rename_theme_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinventory",
            name="allocation_priority_override",
            field=models.BooleanField(
                blank=True,
                editable=False,
                help_text="未設定時依出廠年月自動判斷；有值代表人員手動開啟或關閉。",
                null=True,
                verbose_name="優先配車人工設定",
            ),
        ),
    ]
