# Generated by Django 5.2.17 on 2026-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0160_inventory_allocation_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinventory",
            name="acquisition_type",
            field=models.CharField(
                choices=[("company", "公司進車"), ("dealer_transfer", "經銷商調車")],
                default="company",
                max_length=20,
                verbose_name="車輛來源",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="transfer_source_name",
            field=models.CharField(
                blank=True,
                help_text="經銷商調車時填寫跟哪一家經銷商調車。",
                max_length=120,
                verbose_name="調車來源",
            ),
        ),
    ]
