# Generated by Django 5.2.17 on 2026-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0161_inventory_acquisition_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinventory",
            name="acquisition_type",
            field=models.CharField(
                choices=[("company", "公司進車"), ("dealer_transfer", "車行調車")],
                default="company",
                max_length=20,
                verbose_name="車輛來源",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinventory",
            name="transfer_source_name",
            field=models.CharField(
                blank=True,
                help_text="車行調車時填寫跟哪一家車行調車。",
                max_length=120,
                verbose_name="調車來源",
            ),
        ),
    ]
