# Generated by Django 5.2.17 on 2026-10-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0162_rename_dealer_transfer_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="dealer_reward_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="建立訂單時適用的車行附加獎勵方案；空白表示舊訂單，顯示時依日期查詢主檔。",
                verbose_name="車行附加獎勵快照",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="dealer_reward_snapshot_locked_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="附加獎勵快照保存時間",
            ),
        ),
    ]
