# Generated by Django 5.2.17 on 2026-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0164_order_dealer_reward_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="fulfillment_confirmed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="贈品與履約確認時間"
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="fulfillment_confirmed_by",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=150,
                verbose_name="贈品與履約確認人",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_control_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="車控與電池合約確認時間",
            ),
        ),
        migrations.AddField(
            model_name="orderoperationsprofile",
            name="vehicle_control_confirmed_by",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=150,
                verbose_name="車控與電池合約確認人",
            ),
        ),
    ]
