# Generated by Django 5.2.17 on 2026-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0165_order_delivery_confirmations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccountauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "建立帳號"),
                    ("update", "修改帳號"),
                    ("activate", "啟用帳號"),
                    ("deactivate", "停用帳號"),
                    ("reset_password", "重設密碼"),
                    ("change_password", "使用者變更密碼"),
                    ("grant_admin", "授予管理者"),
                    ("revoke_admin", "移除管理者"),
                    ("delete_draft", "刪除草稿"),
                ],
                max_length=30,
                verbose_name="動作",
            ),
        ),
    ]
