# Generated by Django 5.2.17 on 2026-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0167_audit_log_mark_draft_deletions"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="old_owner_household_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="舊車主戶籍"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="old_owner_phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="舊車主電話"
            ),
        ),
    ]
