# Generated by Django 5.2.17 on 2026-10-10 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0169_old_owner_markers_and_contact_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinventory",
            name="disposition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transfer_out", "調出"),
                    ("dealer_pickup", "車行領車"),
                    ("sold", "一般售出"),
                ],
                max_length=20,
                verbose_name="去向",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="disposition_dealer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"source_type": "dealer"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disposed_vehicles",
                to="sales.salessource",
                verbose_name="去向車行",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="disposition_dealer_name",
            field=models.CharField(
                blank=True,
                help_text="對不到車行主檔時保留原文，例如「工廠」或尚未建檔的車行。",
                max_length=120,
                verbose_name="去向對象（原文）",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="disposition_on",
            field=models.DateField(blank=True, null=True, verbose_name="去向日期"),
        ),
        migrations.AddField(
            model_name="vehicleinventory",
            name="note",
            field=models.TextField(blank=True, verbose_name="備註"),
        ),
        migrations.AlterField(
            model_name="vehicleinventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "可銷售"),
                    ("reserved", "已預留"),
                    ("delivered", "已交車"),
                    ("condition_issue", "車況異常（暫停配車）"),
                    ("sold", "已售出"),
                    ("transferred_out", "已調出"),
                    ("inactive", "停用"),
                ],
                default="available",
                max_length=30,
                verbose_name="庫存狀態",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinventoryhistory",
            name="status_snapshot",
            field=models.CharField(
                choices=[
                    ("available", "可銷售"),
                    ("reserved", "已預留"),
                    ("delivered", "已交車"),
                    ("condition_issue", "車況異常（暫停配車）"),
                    ("sold", "已售出"),
                    ("transferred_out", "已調出"),
                    ("inactive", "停用"),
                ],
                max_length=30,
                verbose_name="當下狀態",
            ),
        ),
    ]
