# Generated by Django 5.2.17 on 2026-10-10 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0170_inventory_disposition_and_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTransferSignoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "dealer_name",
                    models.CharField(max_length=120, verbose_name="調往對象"),
                ),
                (
                    "vehicles_snapshot",
                    models.JSONField(
                        default=list, editable=False, verbose_name="簽署當下車輛"
                    ),
                ),
                (
                    "company_snapshot",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="簽收單公司抬頭"
                    ),
                ),
                ("signer_name", models.CharField(max_length=60, verbose_name="領車人")),
                (
                    "signer_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="領車人電話"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="備註"),
                ),
                (
                    "signature_image",
                    models.FileField(
                        editable=False,
                        upload_to="inventory/transfer-signoffs/%Y/%m/",
                        verbose_name="簽名",
                    ),
                ),
                (
                    "signed_pdf",
                    models.FileField(
                        editable=False,
                        upload_to="inventory/transfer-signoffs/%Y/%m/",
                        verbose_name="簽收單",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="內容指紋"
                    ),
                ),
                (
                    "pdf_sha256",
                    models.CharField(
                        editable=False, max_length=64, verbose_name="簽收單 SHA-256"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(editable=False, verbose_name="簽署時間"),
                ),
                (
                    "staff_name",
                    models.CharField(
                        editable=False, max_length=60, verbose_name="經手人"
                    ),
                ),
                (
                    "client_ip",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="簽署 IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=300,
                        verbose_name="簽署裝置",
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="作廢時間"
                    ),
                ),
                (
                    "voided_by",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=150,
                        verbose_name="作廢人員",
                    ),
                ),
                (
                    "void_reason",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=300,
                        verbose_name="作廢原因",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"source_type": "dealer"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_signoffs",
                        to="sales.salessource",
                        verbose_name="調往車行",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="經手帳號",
                    ),
                ),
                (
                    "vehicles",
                    models.ManyToManyField(
                        related_name="transfer_signoffs",
                        to="sales.vehicleinventory",
                        verbose_name="調出車輛",
                    ),
                ),
            ],
            options={
                "verbose_name": "調車簽收",
                "verbose_name_plural": "調車簽收",
                "ordering": ["-signed_at", "-id"],
            },
        ),
    ]
