# Generated by Django 5.2.17 on 2026-10-10 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0174_move_plate_selection_other_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="方案名稱"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("industry", "工業局"),
                            ("environment", "環境部"),
                            ("local", "地方政府"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="單位",
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="可留空；帶入訂單後仍可逐筆修改金額。",
                        max_digits=12,
                        null=True,
                        verbose_name="預設金額",
                    ),
                ),
                (
                    "requires_old_vehicle",
                    models.BooleanField(
                        default=False,
                        help_text="勾選後，訂車選了此方案會開啟汰舊補助流程（舊車牌、舊車主與文件）。",
                        verbose_name="汰舊類（需要舊車與舊車主資料）",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="啟用中")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "補助方案",
                "verbose_name_plural": "補助方案",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="subsidyitem",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="sales.subsidyprogram",
                verbose_name="補助方案",
            ),
        ),
    ]
