# Generated by Django 5.2.17 on 2026-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0176_seed_subsidy_programs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicletransfersignoff",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "調車簽收",
                "verbose_name_plural": "調車簽收",
            },
        ),
        migrations.AddField(
            model_name="vehicletransfersignoff",
            name="prepared_by",
            field=models.CharField(
                blank=True, editable=False, max_length=150, verbose_name="預備人員"
            ),
        ),
        migrations.AddField(
            model_name="vehicletransfersignoff",
            name="status",
            field=models.CharField(
                choices=[("pending", "待簽收"), ("signed", "已簽收")],
                db_index=True,
                default="signed",
                max_length=10,
                verbose_name="狀態",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletransfersignoff",
            name="fingerprint",
            field=models.CharField(
                blank=True, editable=False, max_length=64, verbose_name="內容指紋"
            ),
        ),
        migrations.AlterField(
            model_name="vehicletransfersignoff",
            name="pdf_sha256",
            field=models.CharField(
                blank=True, editable=False, max_length=64, verbose_name="簽收單 SHA-256"
            ),
        ),
        migrations.AlterField(
            model_name="vehicletransfersignoff",
            name="signature_image",
            field=models.FileField(
                blank=True,
                editable=False,
                upload_to="inventory/transfer-signoffs/%Y/%m/",
                verbose_name="簽名",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletransfersignoff",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="簽署時間"
            ),
        ),
        migrations.AlterField(
            model_name="vehicletransfersignoff",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                editable=False,
                upload_to="inventory/transfer-signoffs/%Y/%m/",
                verbose_name="簽收單",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletransfersignoff",
            name="signer_name",
            field=models.CharField(blank=True, max_length=60, verbose_name="領車人"),
        ),
    ]
